#!/usr/bin/env python3
"""Build shared macros for the period-specific pair lifecycle split."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


LIFECYCLE = OUTPUT_DIR / "exhibits" / "vehicle_transition_pair_lifecycle.jsonl"
DECOMPOSITION = (
    OUTPUT_DIR / "exhibits" / "vehicle_transition_pair_decomposition.jsonl"
)
VALUES = OUTPUT_DIR / "exhibits" / "vehicle_transition_pair_lifecycle_values.tex"

GROUPS = (
    ("Entry", "first_endpoint_pair_observed_after_baseline_window"),
    ("Reactivation", "endpoint_pair_reactivated"),
    ("RoleTurnover", "vehicle_role_turnover_in_continuing_endpoint_pairs"),
    ("Exit", "endpoint_pair_last_observed_before_comparison_window"),
)
METRICS = (
    ("Count", "count_share"),
    ("Value", "strict_intermediation_value_share"),
)


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        if column not in selected.columns:
            raise ValueError(f"pair-lifecycle data lack selector column {column}")
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def _signed_pp(value: float, digits: int) -> str:
    if abs(value) < 0.5 * 10 ** (-digits):
        value = 0.0
    return f"${value:+.{digits}f}$ pp"


def _pct(value: float) -> str:
    return f"{100.0 * value:.1f}\\%"


def render_pair_turnover_lifecycle_values(
    lifecycle: pd.DataFrame,
    decomposition: pd.DataFrame,
) -> str:
    """Validate the lifecycle identity and render paper/deck quantities."""

    lines = [
        "% Generated by scripts/tabulate/build_pair_turnover_lifecycle_values.py; do not edit."
    ]
    for prefix, metric in METRICS:
        rows: dict[str, pd.Series] = {}
        for name, category in GROUPS:
            rows[name] = _single(
                lifecycle,
                metric=metric,
                aggregation_level="lifecycle_group",
                lifecycle_category=category,
            )
        net = _single(
            lifecycle,
            metric=metric,
            aggregation_level="exclusive_total",
            lifecycle_category="one_window_only_total",
        )
        pooled = _single(
            decomposition,
            metric=metric,
            reporting_scope="pooled",
            baseline_year=2024,
            comparison_year=2026,
            formula_id="midpoint_common_exclusive_support_v1",
        )

        contributions = {
            name: float(row["contribution_pp"]) for name, row in rows.items()
        }
        net_pp = float(net["contribution_pp"])
        pooled_net_pp = 100.0 * float(pooled["exclusive_pair_contribution"])
        total_pp = 100.0 * float(pooled["total_change"])
        for label, value in {
            **contributions,
            "net": net_pp,
            "pooled net": pooled_net_pp,
            "total": total_pp,
        }.items():
            if not math.isfinite(value):
                raise ValueError(f"pair-lifecycle source has non-finite {prefix} {label}")
        if not math.isclose(sum(contributions.values()), net_pp, abs_tol=1e-9):
            raise ValueError(f"{prefix} lifecycle groups do not add to their net term")
        if not math.isclose(net_pp, pooled_net_pp, abs_tol=1e-9):
            raise ValueError(f"{prefix} lifecycle net does not match the decomposition")
        if contributions["Entry"] <= 0 or total_pp <= 0:
            raise ValueError(f"{prefix} entry share requires positive entry and total change")

        offset_pp = net_pp - contributions["Entry"]
        entry_share = contributions["Entry"] / total_pp
        for name, value in (*contributions.items(), ("Offset", offset_pp), ("Net", net_pp)):
            lines.extend(
                [
                    f"\\newcommand{{\\PairLifecycle{prefix}{name}}}"
                    f"{{{_signed_pp(value, 1)}}}",
                    f"\\newcommand{{\\PairLifecycle{prefix}{name}Table}}"
                    f"{{{_signed_pp(value, 2)}}}",
                ]
            )
        lines.append(
            f"\\newcommand{{\\PairLifecycle{prefix}EntryShare}}"
            f"{{{_pct(entry_share)}}}"
        )
    return "\n".join(lines) + "\n"


def run(
    *,
    lifecycle_path: Path = LIFECYCLE,
    decomposition_path: Path = DECOMPOSITION,
    output_path: Path = VALUES,
) -> int:
    for path in (lifecycle_path, decomposition_path):
        require_presentation_source(path)
    rendered = render_pair_turnover_lifecycle_values(
        pd.read_json(lifecycle_path, lines=True),
        pd.read_json(decomposition_path, lines=True),
    )
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lifecycle", type=Path, default=LIFECYCLE)
    parser.add_argument("--decomposition", type=Path, default=DECOMPOSITION)
    parser.add_argument("--output", type=Path, default=VALUES)
    args = parser.parse_args()
    return run(
        lifecycle_path=args.lifecycle,
        decomposition_path=args.decomposition,
        output_path=args.output,
    )


if __name__ == "__main__":
    raise SystemExit(main())
