#!/usr/bin/env python3
"""Build paper/deck macros from the liquidity-provision behavior exhibit."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/liquidity_provision_behavior_exploration.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/liquidity_provision_behavior_deck_values.tex"
BASELINE_YEAR = 2024
COMPARISON_YEAR = 2026


def _pct(value: float, decimals: int = 1) -> str:
    return f"{100 * value:.{decimals}f}\\%"


def _ratio(value: float, decimals: int = 1) -> str:
    return f"${value:.{decimals}f}\\times$"


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def _signed_pp(value: float, decimals: int = 2) -> str:
    points = 100 * value
    if abs(points) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$ pp"
    return f"${points:+.{decimals}f}$ pp"


def _unsigned_pp(value: float, decimals: int = 2) -> str:
    return f"${100 * value:.{decimals}f}$ pp"


def _signed_decimal(value: float, decimals: int = 2) -> str:
    if abs(value) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$"
    return f"${value:+.{decimals}f}$"


def _unsigned_decimal(value: float, decimals: int = 2) -> str:
    return f"${value:.{decimals}f}$"


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def render_liquidity_provision_behavior_deck_values(estimates: pd.DataFrame) -> str:
    required = {"analysis_status", "record_type"}
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"liquidity behavior exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_descriptive").all():
        raise ValueError("liquidity behavior rows are not labelled exploratory_descriptive")
    annual = estimates[estimates["record_type"].eq("annual_stable_allocation")]
    leaders = _single(estimates, record_type="daily_leader_alignment")
    base = _single(annual, year=BASELINE_YEAR)
    end = _single(annual, year=COMPARISON_YEAR)
    if not (
        float(end["stable_intermediary_route_share"]) > float(base["stable_intermediary_route_share"])
        and float(end["stable_capital_share"]) < float(base["stable_capital_share"])
        and float(leaders["weth_capital_leader_share"]) > 0.99
        and float(leaders["stable_excess_leader_share"]) > 0.75
    ):
        raise ValueError("liquidity behavior headline no longer holds; rewrite the slide")
    episode = _single(
        estimates,
        record_type="level_association",
        outcome="intermediary_episode_share",
        predictor="v2_log1p_deposited_capital_usd",
    )
    excess = _single(
        estimates,
        record_type="level_association",
        outcome="vehicle_excess_use_count_ratio",
        predictor="v2_log1p_deposited_capital_usd",
    )
    if float(episode["coefficient"]) <= 0 or float(excess["coefficient"]) <= 0:
        raise ValueError("capital-use level associations are no longer positive")
    lines = [
        "% Generated by scripts/tabulate/build_liquidity_provision_behavior_deck_values.py; do not edit.",
        f"\\newcommand{{\\LiqBehPanelDays}}{{{_integer(int(leaders['days']))}}}",
        f"\\newcommand{{\\LiqBehWethCapitalLeaderDays}}{{{_pct(float(leaders['weth_capital_leader_share']))}}}",
        f"\\newcommand{{\\LiqBehStableExcessLeaderDays}}{{{_pct(float(leaders['stable_excess_leader_share']))}}}",
        f"\\newcommand{{\\LiqBehStableCapitalShareBase}}{{{_pct(float(base['stable_capital_share']))}}}",
        f"\\newcommand{{\\LiqBehStableCapitalShareEnd}}{{{_pct(float(end['stable_capital_share']))}}}",
        f"\\newcommand{{\\LiqBehStableRouteShareBase}}{{{_pct(float(base['stable_intermediary_route_share']))}}}",
        f"\\newcommand{{\\LiqBehStableRouteShareEnd}}{{{_pct(float(end['stable_intermediary_route_share']))}}}",
        f"\\newcommand{{\\LiqBehStableRouteCapitalRatioEnd}}{{{_ratio(float(end['stable_route_to_capital_ratio']))}}}",
        f"\\newcommand{{\\LiqBehLogCapitalEpisodeCoef}}{{{_signed_pp(float(episode['coefficient']))}}}",
        f"\\newcommand{{\\LiqBehLogCapitalEpisodeSE}}{{{_unsigned_pp(float(episode['standard_error']))}}}",
        f"\\newcommand{{\\LiqBehLogCapitalExcessCoef}}{{{_signed_decimal(float(excess['coefficient']))}}}",
        f"\\newcommand{{\\LiqBehLogCapitalExcessSE}}{{{_unsigned_decimal(float(excess['standard_error']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_liquidity_provision_behavior_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
