#!/usr/bin/env python3
"""Build paper/deck macros for the V4 volatility-state result."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/v4_lp_volatility_state.jsonl"
OUTPUT = OUTPUT_DIR / "exhibits/v4_lp_volatility_state_deck_values.tex"


def _single(estimates: pd.DataFrame, *, outcome: str) -> pd.Series:
    selected = estimates[
        estimates["record_type"].eq("v4_lp_volatility_state_regression")
        & estimates["sample_variant"].eq("primary_nonzero_180")
        & estimates["state_window_days"].eq(30)
        & estimates["outcome"].eq(outcome)
    ]
    if len(selected) != 1:
        raise ValueError(f"expected one primary volatility-state row for {outcome}")
    return selected.iloc[0]


def _stars(p_value: float) -> str:
    if p_value < 0.01:
        return "^{***}"
    if p_value < 0.05:
        return "^{**}"
    if p_value < 0.10:
        return "^{*}"
    return ""


def _estimate(value: float, p_value: float) -> str:
    return f"${value:+.3f}{_stars(p_value)}$"


def _se(value: float) -> str:
    return f"${value:.3f}$"


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def render_v4_lp_volatility_state_deck_values(estimates: pd.DataFrame) -> str:
    near = _single(estimates, outcome="near_log1p_incumbent_actions")
    late = _single(estimates, outcome="late_log1p_first_active_origins")
    leave_one_out = estimates[
        estimates["record_type"].eq(
            "v4_lp_volatility_state_leave_one_candidate_out"
        )
    ].copy()
    if len(leave_one_out) != 5:
        raise ValueError("expected five leave-one-candidate-out volatility rows")
    if not (
        float(near["interaction_per_10pp_per_1sd_volatility"]) < 0
        and float(late["interaction_per_10pp_per_1sd_volatility"]) > 0
        and float(near["interaction_holm_p_value"]) < 0.05
        and float(late["interaction_holm_p_value"]) < 0.01
        and float(late["high_state_ci_lower"]) > 0
        and float(late["low_state_ci_upper"]) < 0
        and leave_one_out["interaction_per_10pp_per_1sd_volatility"].gt(0).all()
        and leave_one_out["interaction_p_value"].lt(0.01).all()
    ):
        raise ValueError("V4 volatility-state participation headline no longer holds")
    minimum_leave_one_out = leave_one_out.loc[
        leave_one_out["interaction_per_10pp_per_1sd_volatility"].idxmin()
    ]
    lines = [
        "% Generated by scripts/tabulate/build_v4_lp_volatility_state_deck_values.py; do not edit.",
        f"\\newcommand{{\\VFourVolStateRows}}{{{_integer(int(late['n_observations']))}}}",
        f"\\newcommand{{\\VFourVolStateClusters}}{{{_integer(int(late['date_clusters']))}}}",
        f"\\newcommand{{\\VFourVolStateNearInteractionCoef}}{{{_estimate(float(near['interaction_per_10pp_per_1sd_volatility']), float(near['interaction_holm_p_value']))}}}",
        f"\\newcommand{{\\VFourVolStateNearInteractionSE}}{{{_se(float(near['interaction_standard_error']))}}}",
        f"\\newcommand{{\\VFourVolStateLateMainCoef}}{{{_estimate(float(late['main_effect_per_10pp_at_mean_state']), float(late['main_p_value']))}}}",
        f"\\newcommand{{\\VFourVolStateLateInteractionCoef}}{{{_estimate(float(late['interaction_per_10pp_per_1sd_volatility']), float(late['interaction_holm_p_value']))}}}",
        f"\\newcommand{{\\VFourVolStateLateInteractionSE}}{{{_se(float(late['interaction_standard_error']))}}}",
        f"\\newcommand{{\\VFourVolStateLateLowCoef}}{{{_estimate(float(late['low_state_effect_per_10pp']), float(late['low_state_p_value']))}}}",
        f"\\newcommand{{\\VFourVolStateLateHighCoef}}{{{_estimate(float(late['high_state_effect_per_10pp']), float(late['high_state_p_value']))}}}",
        f"\\newcommand{{\\VFourVolStateLeaveOneMinCoef}}{{{_estimate(float(minimum_leave_one_out['interaction_per_10pp_per_1sd_volatility']), float(minimum_leave_one_out['interaction_p_value']))}}}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    rendered = render_v4_lp_volatility_state_deck_values(
        pd.read_json(args.input, lines=True)
    )
    with atomic_output(args.output) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
