#!/usr/bin/env python3
"""Build display macros for the dated-backing cut of the vehicle rotation.

The rotation is reported into a class, `stable`, whose members differ in what
backs them. These macros carry the class apart: each dated regime's own change in
the same share, on the same denominator and the same matched calendar, plus the
two facts a reader needs before believing the split. The first is the label
ledger, which says whether any candidate's dated backing regime moved between the
endpoint years; a regime term is a change in use only when it does not. The second
is the universe gap between the pooled change measured on the endpoint-candidate
choice panel and the same change measured on the type-level daily panel, which is
what licenses reading these terms beside the headline.

Reads   output/exhibits/e0_vehicle_transition_backing_regime_estimates.jsonl
        output/exhibits/e0_vehicle_transition_backing_regime_support.jsonl
Writes  output/exhibits/vehicle_transition_backing_regime_deck_values.tex
"""

from __future__ import annotations

import math

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits" / "e0_vehicle_transition_backing_regime_estimates.jsonl"
SUPPORT = OUTPUT_DIR / "exhibits" / "e0_vehicle_transition_backing_regime_support.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits" / "vehicle_transition_backing_regime_deck_values.tex"
CODE_SOURCES = ["scripts/tabulate/build_backing_regime_deck_values.py"]

# The headline stratum is the exact two-leg route sample, read at share level so the
# regime terms add to the pooled term. Log odds is published in the exhibit and is
# deliberately not carried into prose macros: it is not additive.
SCOPE = "two_leg"
TRANSFORMATION = "share_level"
WEIGHTINGS = (("Count", "episode", "all_routes"), ("Value", "value", "within_20pct"))
REGIMES = (
    ("Fiat", "fiat_reserve"),
    ("Synthetic", "synthetic"),
    ("OnChain", "on_chain_collateralized"),
    ("Rwa", "mixed_including_rwa"),
    ("NonUsd", "non_usd"),
    ("FraxTransition", "transition_to_full_exogenous_collateralization"),
    ("Pooled", "all_stable"),
)


def _row(frame: pd.DataFrame, **identity: object) -> pd.Series:
    selected = frame
    for key, value in identity.items():
        selected = selected[selected[key] == value]
    if len(selected) != 1:
        terms = ", ".join(f"{key}={value!r}" for key, value in identity.items())
        raise ValueError(
            f"backing-regime exhibit requires one {terms} row; found {len(selected)}"
        )
    return selected.iloc[0]


def _pp(value: float, decimals: int = 2) -> str:
    return f"${100 * value:+.{decimals}f}$ pp"


def _se(value: float, decimals: int = 2) -> str:
    return f"{100 * value:.{decimals}f} pp"


def _share(value: float, decimals: int = 1) -> str:
    return f"{100 * value:.{decimals}f}\\%"


def render(estimates: pd.DataFrame, support: pd.DataFrame) -> str:
    lines = [
        "% Generated by scripts/tabulate/build_backing_regime_deck_values.py.",
        "% Dated backing regimes inside the stablecoin class, on the exact two-leg",
        "% sample and the native-plus-stable denominator of the rotation. Supporting",
        "% scope: the estimates run on the released endpoint-candidate choice panel and",
        "% are not submission-authoritative until the findings freeze admits them.",
        "% Refresh by rerunning scripts/analyze/run_vehicle_transition_e0.py then this builder.",
    ]
    fitted = estimates[
        estimates["routing_scope"].eq(SCOPE) & estimates["transformation"].eq(TRANSFORMATION)
    ]
    ledger = support[support["record_type"].eq("regime_change_ledger")]
    weights = support[
        support["record_type"].eq("support")
        & support["routing_scope"].eq(SCOPE)
        & support["transformation"].eq(TRANSFORMATION)
    ]
    for stem, weighting, value_support in WEIGHTINGS:
        for regime_stem, regime in REGIMES:
            row = _row(
                fitted,
                weighting=weighting,
                value_support=value_support,
                backing_regime=regime,
            )
            for column in ("change", "hac_standard_error", "baseline_daily_mean"):
                if not math.isfinite(float(row[column])):
                    raise ValueError(f"{regime_stem}{stem} has a non-finite {column}")
            lines += [
                f"\\newcommand{{\\Backing{regime_stem}{stem}Change}}{{{_pp(float(row['change']))}}}",
                f"\\newcommand{{\\Backing{regime_stem}{stem}SE}}{{{_se(float(row['hac_standard_error']))}}}",
                f"\\newcommand{{\\Backing{regime_stem}{stem}Base}}{{{_share(float(row['baseline_daily_mean']), 2)}}}",
                f"\\newcommand{{\\Backing{regime_stem}{stem}End}}{{{_share(float(row['comparison_daily_mean']), 2)}}}",
            ]
            weight = _row(
                weights,
                weighting=weighting,
                value_support=value_support,
                backing_regime=regime,
            )
            lines += [
                f"\\newcommand{{\\Backing{regime_stem}{stem}MassBase}}{{{_share(float(weight['baseline_share_of_stable_mass']))}}}",
                f"\\newcommand{{\\Backing{regime_stem}{stem}MassEnd}}{{{_share(float(weight['comparison_share_of_stable_mass']))}}}",
            ]
        reconciliation = _row(
            support[support["record_type"].eq("universe_reconciliation")],
            routing_scope=SCOPE,
            transformation=TRANSFORMATION,
            weighting=weighting,
            value_support=value_support,
        )
        # Three decimals: the two universes agree far inside the second decimal, and
        # rounding that agreement to `0.00 pp` would read as a rounded number rather
        # than as the measured gap it is.
        lines.append(
            f"\\newcommand{{\\Backing{stem}UniverseGap}}{{{_se(float(reconciliation['absolute_difference']), 3)}}}"
        )
    moved = ledger[ledger["label_moves_in_window"].astype(bool)]
    lines += [
        f"\\newcommand{{\\BackingCandidates}}{{{ledger['candidate_address'].nunique():,}}}",
        f"\\newcommand{{\\BackingLabelMovesInWindow}}{{{moved['candidate_address'].nunique():,}}}",
        f"\\newcommand{{\\BackingLabelMovesInPanel}}{{{ledger[ledger['label_moves_in_panel'].astype(bool)]['candidate_address'].nunique():,}}}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    for path in (ESTIMATES, SUPPORT):
        require_presentation_source(path)
    estimates = pd.read_json(ESTIMATES, lines=True)
    support = pd.read_json(SUPPORT, lines=True)
    rendered = render(estimates, support)
    with atomic_output(DECK_VALUES) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {DECK_VALUES.relative_to(OUTPUT_DIR.parent)}")


if __name__ == "__main__":
    main()
