#!/usr/bin/env python3
"""Build paper/deck macros from the route-gas economics exhibit."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/route_gas_economics.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/route_gas_economics_deck_values.tex"
BASELINE_YEAR = 2024
COMPARISON_YEAR = 2026


def _currency(value: float) -> str:
    if abs(value) >= 100:
        return f"\\${value:,.0f}".replace(",", "{,}")
    return f"\\${value:,.2f}".replace(",", "{,}")


def _notional(value: float) -> str:
    if abs(value) >= 1_000_000:
        return f"\\${value / 1_000_000:.1f}m"
    if abs(value) >= 1_000:
        return f"\\${value / 1_000:.1f}k"
    return f"\\${value:,.0f}".replace(",", "{,}")


def _pct(value: float, decimals: int = 1) -> str:
    return f"{100 * value:.{decimals}f}\\%"


def _bps(value: float, decimals: int = 1) -> str:
    return f"{value:.{decimals}f} bp"


def _integer(value: float) -> str:
    return f"{value:,.0f}".replace(",", "{,}")


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def render_route_gas_economics_deck_values(estimates: pd.DataFrame) -> str:
    required = {"analysis_status", "record_type"}
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"route-gas economics exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_descriptive").all():
        raise ValueError("route-gas economics rows are not labelled exploratory_descriptive")
    base = _single(
        estimates,
        record_type="extra_hop_gas_hurdle",
        route_class="stable_vehicle",
        year=BASELINE_YEAR,
    )
    end = _single(
        estimates,
        record_type="extra_hop_gas_hurdle",
        route_class="stable_vehicle",
        year=COMPARISON_YEAR,
    )
    change = _single(
        estimates,
        record_type="endpoint_extra_hop_hurdle_change",
        route_class="stable_vehicle",
    )
    base_feasibility = _single(
        estimates,
        record_type="stable_route_fixed_toll_feasibility",
        route_class="stable_vehicle",
        year=BASELINE_YEAR,
    )
    end_feasibility = _single(
        estimates,
        record_type="stable_route_fixed_toll_feasibility",
        route_class="stable_vehicle",
        year=COMPARISON_YEAR,
    )
    feasibility_change = _single(
        estimates,
        record_type="stable_route_fixed_toll_feasibility_change",
        route_class="stable_vehicle",
    )
    if not (
        float(base["extra_gas_units"]) > 0
        and float(end["extra_gas_units"]) > 0
        and float(end["notional_for_extra_gas_1bp_usd"])
        < float(base["notional_for_extra_gas_1bp_usd"])
        and float(change["one_bp_notional_ratio"]) < 0.25
        and float(end_feasibility["share_fixed_toll_le_25bp"])
        > float(base_feasibility["share_fixed_toll_le_25bp"])
        and float(feasibility_change["median_notional_ratio"]) < 0.25
    ):
        raise ValueError("route-gas hurdle headline no longer holds; rewrite the text")
    lines = [
        "% Generated by scripts/tabulate/build_route_gas_economics_deck_values.py; do not edit.",
        f"\\newcommand{{\\GasStableExtraGasUnitsBase}}{{{_integer(float(base['extra_gas_units']))}}}",
        f"\\newcommand{{\\GasStableExtraGasUnitsEnd}}{{{_integer(float(end['extra_gas_units']))}}}",
        f"\\newcommand{{\\GasStableExtraGasPctBase}}{{{_pct(float(base['extra_gas_units_pct_of_direct']))}}}",
        f"\\newcommand{{\\GasStableExtraGasPctEnd}}{{{_pct(float(end['extra_gas_units_pct_of_direct']))}}}",
        f"\\newcommand{{\\GasStableExtraCostBase}}{{{_currency(float(base['extra_gas_cost_usd_at_year_medians']))}}}",
        f"\\newcommand{{\\GasStableExtraCostEnd}}{{{_currency(float(end['extra_gas_cost_usd_at_year_medians']))}}}",
        f"\\newcommand{{\\GasStableOneBpNotionalBase}}{{{_notional(float(base['notional_for_extra_gas_1bp_usd']))}}}",
        f"\\newcommand{{\\GasStableOneBpNotionalEnd}}{{{_notional(float(end['notional_for_extra_gas_1bp_usd']))}}}",
        f"\\newcommand{{\\GasStableTenBpNotionalEnd}}{{{_notional(float(end['notional_for_extra_gas_10bp_usd']))}}}",
        f"\\newcommand{{\\GasStableMedianNotionalEnd}}{{{_notional(float(end['route_median_notional_usd']))}}}",
        f"\\newcommand{{\\GasStableOneBpRatio}}{{{_pct(float(change['one_bp_notional_ratio']))}}}",
        f"\\newcommand{{\\GasStableRouteMedianNotionalBase}}{{{_notional(float(base_feasibility['median_route_notional_usd']))}}}",
        f"\\newcommand{{\\GasStableRouteMedianNotionalEnd}}{{{_notional(float(end_feasibility['median_route_notional_usd']))}}}",
        f"\\newcommand{{\\GasStableRouteMedianTollBpsBase}}{{{_bps(float(base_feasibility['median_fixed_extra_hop_toll_bps']))}}}",
        f"\\newcommand{{\\GasStableRouteMedianTollBpsEnd}}{{{_bps(float(end_feasibility['median_fixed_extra_hop_toll_bps']))}}}",
        f"\\newcommand{{\\GasStableRouteTenBpShareBase}}{{{_pct(float(base_feasibility['share_fixed_toll_le_10bp']))}}}",
        f"\\newcommand{{\\GasStableRouteTenBpShareEnd}}{{{_pct(float(end_feasibility['share_fixed_toll_le_10bp']))}}}",
        f"\\newcommand{{\\GasStableRouteTwentyFiveBpShareBase}}{{{_pct(float(base_feasibility['share_fixed_toll_le_25bp']))}}}",
        f"\\newcommand{{\\GasStableRouteTwentyFiveBpShareEnd}}{{{_pct(float(end_feasibility['share_fixed_toll_le_25bp']))}}}",
        f"\\newcommand{{\\GasStableRouteMedianNotionalRatio}}{{{_pct(float(feasibility_change['median_notional_ratio']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_route_gas_economics_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
