#!/usr/bin/env python3
"""Build deck macros from the V3/V4 reported-TVL protocol-contrast exhibit."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/v3_v4_tvl_protocol_contrast.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/v3_v4_tvl_protocol_deck_values.tex"
HORIZON_DAYS = 120


def _signed_log_points(value: float) -> str:
    return f"${value:+.3f}$ log pts"


def _unsigned_log_points(value: float) -> str:
    return f"${value:.3f}$ log pts"


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def render_v3_v4_tvl_protocol_deck_values(estimates: pd.DataFrame) -> str:
    required = {
        "analysis_status",
        "horizon_days",
        "outcome",
        "effect_per_10pp_stable_gap_v4_minus_v3",
        "standard_error_per_10pp_stable_gap_v4_minus_v3",
        "p_value",
        "n_observations",
        "date_clusters",
    }
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"V3/V4 TVL protocol exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_protocol_contrast").all():
        raise ValueError("V3/V4 TVL protocol rows are not exploratory_protocol_contrast")
    tvl = _single(
        estimates,
        horizon_days=HORIZON_DAYS,
        outcome="future_delta_log1p_tvl",
    )
    pools = _single(
        estimates,
        horizon_days=HORIZON_DAYS,
        outcome="future_delta_log1p_pool_count",
    )
    if not (
        float(tvl["effect_per_10pp_stable_gap_v4_minus_v3"]) > 0
        and float(pools["effect_per_10pp_stable_gap_v4_minus_v3"]) > 0
        and float(tvl["p_value"]) < 0.01
        and float(pools["p_value"]) < 0.01
        and int(tvl["n_observations"]) > 1_000
    ):
        raise ValueError("V3/V4 TVL protocol deck headline no longer holds")
    lines = [
        "% Generated by scripts/tabulate/build_v3_v4_tvl_protocol_deck_values.py; do not edit.",
        f"\\newcommand{{\\VThreeVFourTvlProtocolRows}}{{{_integer(int(tvl['n_observations']))}}}",
        f"\\newcommand{{\\VThreeVFourTvlProtocolDateClusters}}{{{_integer(int(tvl['date_clusters']))}}}",
        f"\\newcommand{{\\VThreeVFourTvlGrowthLongCoef}}{{{_signed_log_points(float(tvl['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourTvlGrowthLongSE}}{{{_unsigned_log_points(float(tvl['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourPoolFootprintLongCoef}}{{{_signed_log_points(float(pools['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourPoolFootprintLongSE}}{{{_unsigned_log_points(float(pools['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_v3_v4_tvl_protocol_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
