#!/usr/bin/env python3
"""Build paper/deck macros from the stable stress-event exhibit."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/stable_stress_event.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/stable_stress_event_deck_values.tex"


def _pct(value: float, decimals: int = 1) -> str:
    return f"{100.0 * value:.{decimals}f}\\%"


def _signed_pp(value: float, decimals: int = 1) -> str:
    points = 100.0 * value
    if abs(points) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$ pp"
    return f"${points:+.{decimals}f}$ pp"


def _integer(value: int | float) -> str:
    return f"{int(value):,}".replace(",", "{,}")


def _one(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one stable-stress row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def render_stable_stress_event_deck_values(estimates: pd.DataFrame) -> str:
    required = {"analysis_status", "record_type"}
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"stable stress exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_stress_event").all():
        raise ValueError("stable stress rows are not labelled exploratory_stress_event")
    pre_usdc = _one(
        estimates,
        record_type="stable_identity_window",
        stress_window="pre_30d",
        candidate_symbol="USDC",
    )
    stress_usdc = _one(
        estimates,
        record_type="stable_identity_window",
        stress_window="stress_4d",
        candidate_symbol="USDC",
    )
    post_usdt = _one(
        estimates,
        record_type="stable_identity_window",
        stress_window="post_30d",
        candidate_symbol="USDT",
    )
    usdc_change = _one(
        estimates,
        record_type="stable_identity_contrast",
        contrast="stress_minus_pre_usdc_share",
    )
    activity_change = _one(
        estimates,
        record_type="stable_identity_contrast",
        contrast="stress_mean_daily_stable_routes_vs_pre",
    )
    if not (
        float(stress_usdc["stable_route_share"]) > 0.5
        and abs(float(usdc_change["estimate"])) < 0.05
        and float(activity_change["estimate"]) > 0.25
    ):
        raise ValueError("stable stress-event identity pattern no longer holds")
    lines = [
        "% Generated by scripts/tabulate/build_stable_stress_event_deck_values.py; do not edit.",
        f"\\newcommand{{\\StressEventPreUsdcShare}}{{{_pct(float(pre_usdc['stable_route_share']))}}}",
        f"\\newcommand{{\\StressEventStressUsdcShare}}{{{_pct(float(stress_usdc['stable_route_share']))}}}",
        f"\\newcommand{{\\StressEventUsdcShareChange}}{{{_signed_pp(float(usdc_change['estimate']))}}}",
        f"\\newcommand{{\\StressEventStableActivityRise}}{{{_pct(float(activity_change['estimate']))}}}",
        f"\\newcommand{{\\StressEventStressRoutesPerDay}}{{{_integer(float(stress_usdc['mean_daily_stable_routes']))}}}",
        f"\\newcommand{{\\StressEventPostUsdtShare}}{{{_pct(float(post_usdt['stable_route_share']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_stable_stress_event_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
