#!/usr/bin/env python3
"""Build paper/deck macros from the market-size vehicle screen."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/vehicle_market_size_exploration.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/vehicle_market_size_deck_values.tex"
BASELINE_YEAR = 2024
COMPARISON_YEAR = 2026


def _pct(value: float, decimals: int = 1) -> str:
    return f"{100 * value:.{decimals}f}\\%"


def _signed_pp(value: float, decimals: int = 1) -> str:
    points = 100 * value
    if abs(points) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$ pp"
    return f"${points:+.{decimals}f}$ pp"


def _unsigned_pp(value: float, decimals: int = 1) -> str:
    return f"${100 * value:.{decimals}f}$ pp"


def _integer(value: float | int) -> str:
    return f"{int(round(float(value))):,}"


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def render_vehicle_market_size_deck_values(estimates: pd.DataFrame) -> str:
    required = {"analysis_status", "record_type"}
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"market-size exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_descriptive").all():
        raise ValueError("market-size rows are not labelled exploratory_descriptive")
    thin = _single(
        estimates,
        record_type="daily_market_size_change",
        estimand="thin_1_5",
    )
    thick = _single(
        estimates,
        record_type="daily_market_size_change",
        estimand="thick_gt100",
    )
    gap = _single(
        estimates,
        record_type="daily_market_size_change",
        estimand="thick_minus_thin",
    )
    if not (
        int(thin["baseline_year"]) == BASELINE_YEAR
        and int(thin["comparison_year"]) == COMPARISON_YEAR
        and float(thin["change"]) > 0
        and float(thick["change"]) > 0
        and float(gap["baseline_mean"]) > 0
        and float(gap["comparison_mean"]) > 0
        and float(gap["comparison_mean"]) > float(thin["comparison_mean"])
    ):
        raise ValueError("market-size headline no longer holds; rewrite paper/deck text")
    entry_thick_base = _single(
        estimates,
        record_type="entry_market_size_summary",
        entry_year=BASELINE_YEAR,
        size_bin="thick_gt100",
    )
    entry_thick_end = _single(
        estimates,
        record_type="entry_market_size_summary",
        entry_year=COMPARISON_YEAR,
        size_bin="thick_gt100",
    )
    entry_thin_end = _single(
        estimates,
        record_type="entry_market_size_summary",
        entry_year=COMPARISON_YEAR,
        size_bin="thin_1_5",
    )
    entry_thick_change = float(entry_thick_end["stable_count_share"]) - float(
        entry_thick_base["stable_count_share"]
    )
    if not (
        float(entry_thick_end["stable_count_share"]) > float(entry_thin_end["stable_count_share"])
        and entry_thick_change > 0
        and float(entry_thick_end["entry_route_mass_share"]) > 0
    ):
        raise ValueError("entry market-size headline no longer holds; rewrite paper/deck text")
    lines = [
        "% Generated by scripts/tabulate/build_vehicle_market_size_deck_values.py; do not edit.",
        f"\\newcommand{{\\MarketSizeThinShareBase}}{{{_pct(float(thin['baseline_mean']))}}}",
        f"\\newcommand{{\\MarketSizeThinShareEnd}}{{{_pct(float(thin['comparison_mean']))}}}",
        f"\\newcommand{{\\MarketSizeThinChange}}{{{_signed_pp(float(thin['change']))}}}",
        f"\\newcommand{{\\MarketSizeThinChangeSE}}{{{_unsigned_pp(float(thin['standard_error']))}}}",
        f"\\newcommand{{\\MarketSizeThickShareBase}}{{{_pct(float(thick['baseline_mean']))}}}",
        f"\\newcommand{{\\MarketSizeThickShareEnd}}{{{_pct(float(thick['comparison_mean']))}}}",
        f"\\newcommand{{\\MarketSizeThickChange}}{{{_signed_pp(float(thick['change']))}}}",
        f"\\newcommand{{\\MarketSizeThickChangeSE}}{{{_unsigned_pp(float(thick['standard_error']))}}}",
        f"\\newcommand{{\\MarketSizeThickMinusThinBase}}{{{_signed_pp(float(gap['baseline_mean']))}}}",
        f"\\newcommand{{\\MarketSizeThickMinusThinEnd}}{{{_signed_pp(float(gap['comparison_mean']))}}}",
        f"\\newcommand{{\\MarketSizeThickMinusThinChange}}{{{_signed_pp(float(gap['change']))}}}",
        f"\\newcommand{{\\MarketSizeThickMinusThinChangeSE}}{{{_unsigned_pp(float(gap['standard_error']))}}}",
        f"\\newcommand{{\\MarketSizeEntryThickShareBase}}{{{_pct(float(entry_thick_base['stable_count_share']))}}}",
        f"\\newcommand{{\\MarketSizeEntryThickShareEnd}}{{{_pct(float(entry_thick_end['stable_count_share']))}}}",
        f"\\newcommand{{\\MarketSizeEntryThickChange}}{{{_signed_pp(entry_thick_change)}}}",
        f"\\newcommand{{\\MarketSizeEntryThickMassEnd}}{{{_pct(float(entry_thick_end['entry_route_mass_share']))}}}",
        f"\\newcommand{{\\MarketSizeEntryThickPairsEnd}}{{{_integer(entry_thick_end['pairs'])}}}",
        f"\\newcommand{{\\MarketSizeEntryThinShareEnd}}{{{_pct(float(entry_thin_end['stable_count_share']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_vehicle_market_size_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
