#!/usr/bin/env python3
"""Build paper/deck macros from the vehicle-dominance mechanism sweep."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/vehicle_dominance_mechanism_sweep.jsonl"
SUPPORT = OUTPUT_DIR / "exhibits/vehicle_dominance_mechanism_support.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/vehicle_mechanism_sweep_deck_values.tex"


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def _signed_pp(value: float, decimals: int = 1) -> str:
    if abs(value) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$ pp"
    return f"${value:+.{decimals}f}$ pp"


def _unsigned_pp(value: float, decimals: int = 1) -> str:
    return f"${value:.{decimals}f}$ pp"


def _effect(
    estimates: pd.DataFrame,
    *,
    model_id: str,
    regressor: str,
) -> pd.Series:
    return _single(
        estimates,
        claim_status="provisional_exploratory",
        experiment_family="vehicle_dominance_mechanism_sweep",
        metric="count_share",
        model_id=model_id,
        regressor=regressor,
    )


def render_vehicle_mechanism_sweep_deck_values(
    estimates: pd.DataFrame, support: pd.DataFrame
) -> str:
    """Return guarded LaTeX macros for the mechanism-sweep headline."""

    support_row = _single(
        support,
        claim_status="provisional_exploratory",
        experiment_family="vehicle_dominance_mechanism_sweep",
        metric="count_share",
    )
    turn_on_thin = _effect(
        estimates,
        model_id="turn_on_lpm",
        regressor="baseline_log_market_routes",
    )
    turn_on_direct = _effect(
        estimates,
        model_id="turn_on_lpm",
        regressor="baseline_direct_route_share",
    )
    turn_on_complex = _effect(
        estimates,
        model_id="turn_on_lpm",
        regressor="baseline_complex_route_share",
    )
    leader_thin = _effect(
        estimates,
        model_id="leader_switch_lpm",
        regressor="baseline_log_market_routes",
    )
    if not (
        float(turn_on_thin["coefficient_pp"]) < 0
        and float(leader_thin["coefficient_pp"]) < 0
        and float(turn_on_direct["coefficient_pp"]) > 0
        and float(turn_on_complex["coefficient_pp"]) > 0
        and float(turn_on_thin["p_value"]) < 0.01
        and float(leader_thin["p_value"]) < 0.01
    ):
        raise ValueError("vehicle mechanism-sweep headline no longer holds")
    lines = [
        "% Generated by scripts/tabulate/build_vehicle_mechanism_sweep_deck_values.py; do not edit.",
        f"\\newcommand{{\\MechanismScreenRows}}{{{_integer(int(support_row['rows']))}}}",
        f"\\newcommand{{\\MechanismScreenPairs}}{{{_integer(int(support_row['ordered_pairs']))}}}",
        f"\\newcommand{{\\MechanismScreenDays}}{{{_integer(int(support_row['month_days']))}}}",
        f"\\newcommand{{\\MechanismTurnOnThinCoef}}{{{_signed_pp(float(turn_on_thin['coefficient_pp']))}}}",
        f"\\newcommand{{\\MechanismTurnOnThinSE}}{{{_unsigned_pp(float(turn_on_thin['standard_error_pp']))}}}",
        f"\\newcommand{{\\MechanismTurnOnThinOneSd}}{{{_signed_pp(float(turn_on_thin['one_sd_effect_pp']))}}}",
        f"\\newcommand{{\\MechanismTurnOnDirectCoef}}{{{_signed_pp(float(turn_on_direct['coefficient_pp']))}}}",
        f"\\newcommand{{\\MechanismTurnOnDirectSE}}{{{_unsigned_pp(float(turn_on_direct['standard_error_pp']))}}}",
        f"\\newcommand{{\\MechanismTurnOnComplexCoef}}{{{_signed_pp(float(turn_on_complex['coefficient_pp']))}}}",
        f"\\newcommand{{\\MechanismTurnOnComplexSE}}{{{_unsigned_pp(float(turn_on_complex['standard_error_pp']))}}}",
        f"\\newcommand{{\\MechanismLeaderThinCoef}}{{{_signed_pp(float(leader_thin['coefficient_pp']))}}}",
        f"\\newcommand{{\\MechanismLeaderThinSE}}{{{_unsigned_pp(float(leader_thin['standard_error_pp']))}}}",
        f"\\newcommand{{\\MechanismLeaderThinOneSd}}{{{_signed_pp(float(leader_thin['one_sd_effect_pp']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(
    *,
    estimates_path: Path = ESTIMATES,
    support_path: Path = SUPPORT,
    output_path: Path = DECK_VALUES,
) -> int:
    require_presentation_source(estimates_path)
    require_presentation_source(support_path)
    estimates = pd.read_json(estimates_path, lines=True)
    support = pd.read_json(support_path, lines=True)
    rendered = render_vehicle_mechanism_sweep_deck_values(estimates, support)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--support", type=Path, default=SUPPORT)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(
        estimates_path=args.estimates,
        support_path=args.support,
        output_path=args.output,
    )


if __name__ == "__main__":
    raise SystemExit(main())
