#!/usr/bin/env python3
"""Build paper and deck values for stable-to-stable intermediary identity."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.runtime import atomic_output


RESULTS = OUTPUT_DIR / "exhibits/stable_stable_vehicle_decomposition.jsonl"
ROBUSTNESS = OUTPUT_DIR / "exhibits/stable_stable_vehicle_robustness.jsonl"
VALUES = OUTPUT_DIR / "exhibits/stable_stable_vehicle_values.tex"


def _signed_pp(value: float) -> str:
    return f"${100.0 * value:+.1f}$ pp"


def _percent(value: float) -> str:
    return f"{100.0 * value:.1f}\\%"


def render_stable_stable_vehicle_values(
    results: pd.DataFrame,
    robustness: pd.DataFrame,
) -> str:
    """Render the issuer split and its two day-concentration checks."""

    result_required = {
        "metric",
        "intermediary_group",
        "common_calendar_days",
        "stable_share_contribution_baseline",
        "stable_share_contribution_comparison",
        "stable_share_contribution_change",
    }
    robustness_required = {
        "metric",
        "year",
        "common_calendar_days",
        "active_days",
        "top_decile_trimmed_mean_stable_contribution",
        "pooled_mass_stable_contribution",
    }
    missing_results = sorted(result_required - set(results.columns))
    missing_robustness = sorted(robustness_required - set(robustness.columns))
    if missing_results:
        raise ValueError(f"stable-to-stable results lack columns: {missing_results}")
    if missing_robustness:
        raise ValueError(
            f"stable-to-stable robustness lacks columns: {missing_robustness}"
        )
    if set(results["common_calendar_days"]) != {181} or set(
        robustness["common_calendar_days"]
    ) != {181}:
        raise ValueError("stable-to-stable presentation requires 181 common days")

    value = results[results["metric"].eq("strict_intermediation_value_share")]
    expected_groups = {"native", "usdt", "usdc", "dai", "other_stable"}
    if set(value["intermediary_group"]) != expected_groups or len(value) != 5:
        raise ValueError("stable-to-stable value results lack an intermediary group")

    def group(name: str) -> pd.Series:
        selected = value[value["intermediary_group"].eq(name)]
        if len(selected) != 1:
            raise ValueError(f"expected one stable-to-stable value row for {name}")
        return selected.iloc[0]

    usdt = group("usdt")
    native = group("native")
    other_stable = value[value["intermediary_group"].isin({"usdc", "dai", "other_stable"})]
    stable_total_change = float(
        value[value["intermediary_group"].ne("native")][
            "stable_share_contribution_change"
        ].sum()
    )
    other_stable_change = float(other_stable["stable_share_contribution_change"].sum())
    if not np.isclose(
        float(usdt["stable_share_contribution_change"]) + other_stable_change,
        stable_total_change,
        atol=1e-10,
    ):
        raise ValueError("stable-to-stable issuer split does not reconcile")

    robust_value = robustness[
        robustness["metric"].eq("strict_intermediation_value_share")
    ].set_index("year")
    if set(robust_value.index) != {2024, 2026}:
        raise ValueError("stable-to-stable robustness lacks an endpoint year")
    trim_change = float(
        robust_value.loc[2026, "top_decile_trimmed_mean_stable_contribution"]
        - robust_value.loc[2024, "top_decile_trimmed_mean_stable_contribution"]
    )
    pooled_change = float(
        robust_value.loc[2026, "pooled_mass_stable_contribution"]
        - robust_value.loc[2024, "pooled_mass_stable_contribution"]
    )
    if set(robust_value["active_days"]) != {181}:
        raise ValueError("stable-to-stable value channel is not active on all common days")

    lines = [
        "% Generated by scripts/tabulate/build_stable_stable_vehicle_values.py; do not edit.",
        "% Issuer identity within the stable-to-stable endpoint contribution.",
        f"\\newcommand{{\\StableStableValueContribution}}{{{_signed_pp(stable_total_change)}}}",
        f"\\newcommand{{\\StableStableUsdtValueContribution}}{{{_signed_pp(float(usdt['stable_share_contribution_change']))}}}",
        f"\\newcommand{{\\StableStableOtherValueContribution}}{{{_signed_pp(other_stable_change)}}}",
        f"\\newcommand{{\\StableStableNativeValueContribution}}{{{_signed_pp(float(native['stable_share_contribution_change']))}}}",
        f"\\newcommand{{\\StableStableTrimmedValueChange}}{{{_signed_pp(trim_change)}}}",
        f"\\newcommand{{\\StableStablePooledValueChange}}{{{_signed_pp(pooled_change)}}}",
        f"\\newcommand{{\\StableStableTrimmedBase}}{{{_percent(float(robust_value.loc[2024, 'top_decile_trimmed_mean_stable_contribution']))}}}",
        f"\\newcommand{{\\StableStableTrimmedEnd}}{{{_percent(float(robust_value.loc[2026, 'top_decile_trimmed_mean_stable_contribution']))}}}",
        "\\newcommand{\\StableStableActiveDays}{181}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=RESULTS)
    parser.add_argument("--robustness", type=Path, default=ROBUSTNESS)
    parser.add_argument("--values", type=Path, default=VALUES)
    args = parser.parse_args()
    rendered = render_stable_stable_vehicle_values(
        pd.read_json(args.results, lines=True),
        pd.read_json(args.robustness, lines=True),
    )
    with atomic_output(args.values) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
