#!/usr/bin/env python3
"""Build deck macros from the V3/V4 LP-flow protocol-contrast exhibit."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/v3_v4_lp_flow_protocol_contrast.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/v3_v4_lp_flow_protocol_deck_values.tex"
HORIZON_DAYS = 120
WEEK_HORIZON_DAYS = 7
MONTH_HORIZON_DAYS = 30


def _signed_log_points(value: float) -> str:
    if abs(value) < 0.0005:
        return "$0.000$ log pts"
    return f"${value:+.3f}$ log pts"


def _unsigned_log_points(value: float) -> str:
    return f"${value:.3f}$ log pts"


def _signed_percentage_points(value: float) -> str:
    if abs(value) < 0.0005:
        return "$0.0$ pp"
    return f"${100 * value:+.1f}$ pp"


def _unsigned_percentage_points(value: float) -> str:
    return f"${100 * value:.1f}$ pp"


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def _contrast_row(
    estimates: pd.DataFrame, *, outcome: str, horizon_days: int = HORIZON_DAYS
) -> pd.Series:
    return _single(
        estimates,
        horizon_days=horizon_days,
        outcome=outcome,
        term="v4_x_stable_gap",
    )


def render_v3_v4_lp_flow_protocol_deck_values(estimates: pd.DataFrame) -> str:
    required = {
        "activity_controls",
        "analysis_status",
        "date_clusters",
        "effect_per_10pp_stable_gap_v4_minus_v3",
        "fixed_effects",
        "horizon_days",
        "n_observations",
        "outcome",
        "p_value",
        "record_type",
        "standard_error_per_10pp_stable_gap_v4_minus_v3",
        "term",
    }
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"V3/V4 LP-flow protocol exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_protocol_contrast").all():
        raise ValueError("V3/V4 LP-flow protocol rows are not exploratory_protocol_contrast")
    gross = _contrast_row(estimates, outcome="future_log1p_gross_lp_flow_usd")
    add = _contrast_row(estimates, outcome="future_log1p_add_lp_flow_usd")
    remove = _contrast_row(estimates, outcome="future_log1p_remove_lp_flow_usd")
    narrow_week = _contrast_row(
        estimates,
        outcome="future_narrow_medium_flow_value_share",
        horizon_days=WEEK_HORIZON_DAYS,
    )
    narrow_month = _contrast_row(
        estimates,
        outcome="future_narrow_medium_flow_value_share",
        horizon_days=MONTH_HORIZON_DAYS,
    )
    narrow_long = _contrast_row(
        estimates,
        outcome="future_narrow_medium_flow_value_share",
    )
    broad_week = _contrast_row(
        estimates,
        outcome="future_broad_flow_value_share",
        horizon_days=WEEK_HORIZON_DAYS,
    )
    broad_month = _contrast_row(
        estimates,
        outcome="future_broad_flow_value_share",
        horizon_days=MONTH_HORIZON_DAYS,
    )
    broad_long = _contrast_row(estimates, outcome="future_broad_flow_value_share")
    if not (
        abs(float(gross["effect_per_10pp_stable_gap_v4_minus_v3"])) < 0.05
        and abs(float(add["effect_per_10pp_stable_gap_v4_minus_v3"])) < 0.05
        and float(remove["effect_per_10pp_stable_gap_v4_minus_v3"]) > 0.03
        and float(remove["p_value"]) < 0.05
        and int(remove["n_observations"]) > 5_000
        and float(narrow_week["effect_per_10pp_stable_gap_v4_minus_v3"]) > 0.01
        and float(narrow_month["effect_per_10pp_stable_gap_v4_minus_v3"]) > 0.01
        and float(narrow_long["effect_per_10pp_stable_gap_v4_minus_v3"]) > 0.002
        and float(broad_week["effect_per_10pp_stable_gap_v4_minus_v3"]) < -0.01
        and float(broad_month["effect_per_10pp_stable_gap_v4_minus_v3"]) < -0.01
        and float(broad_long["effect_per_10pp_stable_gap_v4_minus_v3"]) < -0.002
        and float(narrow_week["p_value"]) < 0.01
        and float(narrow_month["p_value"]) < 0.01
        and float(narrow_long["p_value"]) < 0.01
    ):
        raise ValueError("V3/V4 LP-flow protocol deck headline no longer holds")
    lines = [
        "% Generated by scripts/tabulate/build_v3_v4_lp_flow_protocol_deck_values.py; do not edit.",
        f"\\newcommand{{\\VThreeVFourLpFlowProtocolRows}}{{{_integer(int(remove['n_observations']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowProtocolDateClusters}}{{{_integer(int(remove['date_clusters']))}}}",
        "\\newcommand{\\VThreeVFourLpFlowProtocolHorizon}{120 days}",
        "\\newcommand{\\VThreeVFourLpFlowProtocolFixedEffects}{candidate-date and protocol}",
        f"\\newcommand{{\\VThreeVFourLpFlowGrossLongCoef}}{{{_signed_log_points(float(gross['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowGrossLongSE}}{{{_unsigned_log_points(float(gross['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowAddLongCoef}}{{{_signed_log_points(float(add['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowAddLongSE}}{{{_unsigned_log_points(float(add['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowRemoveLongCoef}}{{{_signed_log_points(float(remove['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowRemoveLongSE}}{{{_unsigned_log_points(float(remove['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowNarrowWeekCoef}}{{{_signed_percentage_points(float(narrow_week['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowNarrowWeekSE}}{{{_unsigned_percentage_points(float(narrow_week['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowNarrowMonthCoef}}{{{_signed_percentage_points(float(narrow_month['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowNarrowMonthSE}}{{{_unsigned_percentage_points(float(narrow_month['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowNarrowLongCoef}}{{{_signed_percentage_points(float(narrow_long['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowNarrowLongSE}}{{{_unsigned_percentage_points(float(narrow_long['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowBroadWeekCoef}}{{{_signed_percentage_points(float(broad_week['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowBroadWeekSE}}{{{_unsigned_percentage_points(float(broad_week['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowBroadMonthCoef}}{{{_signed_percentage_points(float(broad_month['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowBroadMonthSE}}{{{_unsigned_percentage_points(float(broad_month['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowBroadLongCoef}}{{{_signed_percentage_points(float(broad_long['effect_per_10pp_stable_gap_v4_minus_v3']))}}}",
        f"\\newcommand{{\\VThreeVFourLpFlowBroadLongSE}}{{{_unsigned_percentage_points(float(broad_long['standard_error_per_10pp_stable_gap_v4_minus_v3']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_v3_v4_lp_flow_protocol_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
