#!/usr/bin/env python3
"""Build deck macros from the V4 flash-accounting/stable-gap interaction exhibit."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/v4_flash_gap_interaction_exploration.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/v4_flash_gap_deck_values.tex"
HORIZON_DAYS = 120


def _signed(value: float, unit: str, decimals: int = 3) -> str:
    if abs(value) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$ {unit}"
    return f"${value:+.{decimals}f}$ {unit}"


def _unsigned(value: float, unit: str, decimals: int = 3) -> str:
    return f"${value:.{decimals}f}$ {unit}"


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def _interaction_row(
    estimates: pd.DataFrame,
    *,
    predictor: str,
    outcome: str,
) -> pd.Series:
    return _single(
        estimates,
        horizon_days=HORIZON_DAYS,
        flash_predictor=predictor,
        outcome=outcome,
        term=f"route_capital_gap_5_x_{predictor}",
    )


def _effect(row: pd.Series) -> tuple[float, float, str]:
    coefficient = float(row["coefficient"])
    standard_error = float(row["standard_error"])
    if str(row["outcome"]).endswith("_action_share"):
        return coefficient, standard_error, "pp"
    return 0.01 * coefficient, 0.01 * standard_error, "log pts"


def render_v4_flash_gap_deck_values(estimates: pd.DataFrame) -> str:
    required = {
        "analysis_status",
        "record_type",
        "horizon_days",
        "flash_predictor",
        "outcome",
        "term",
        "coefficient",
        "standard_error",
        "p_value",
        "n_observations",
        "date_clusters",
    }
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"V4 flash-gap exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_mechanism").all():
        raise ValueError("V4 flash-gap rows are not labelled exploratory_mechanism")

    internal_tvl = _interaction_row(
        estimates,
        predictor="internal_tx_share",
        outcome="future_delta_log1p_tvl_usd",
    )
    internal_actions = _interaction_row(
        estimates,
        predictor="internal_tx_share",
        outcome="future_log1p_lp_actions",
    )
    internal_wide = _interaction_row(
        estimates,
        predictor="internal_tx_share",
        outcome="future_wide_very_wide_action_share",
    )
    multileg_wide = _interaction_row(
        estimates,
        predictor="multi_leg_tx_share",
        outcome="future_wide_very_wide_action_share",
    )
    netting_wide = _interaction_row(
        estimates,
        predictor="netting_reduction_share",
        outcome="future_wide_very_wide_action_share",
    )
    if not (
        float(internal_tvl["p_value"]) < 0.01
        and float(internal_actions["p_value"]) < 0.01
        and float(internal_wide["coefficient"]) > 0
        and float(multileg_wide["coefficient"]) > 0
        and float(netting_wide["coefficient"]) < 0
        and float(internal_wide["p_value"]) < 0.01
        and float(multileg_wide["p_value"]) < 0.01
        and float(netting_wide["p_value"]) < 0.01
        and int(internal_wide["n_observations"]) > 1_000
    ):
        raise ValueError("V4 flash-gap interaction deck headline no longer holds")

    rows = {
        "InternalTvl": internal_tvl,
        "InternalActions": internal_actions,
        "InternalWide": internal_wide,
        "MultilegWide": multileg_wide,
        "NettingWide": netting_wide,
    }
    lines = [
        "% Generated by scripts/tabulate/build_v4_flash_gap_deck_values.py; do not edit.",
        f"\\newcommand{{\\VFourFlashGapRows}}{{{_integer(int(internal_wide['n_observations']))}}}",
        f"\\newcommand{{\\VFourFlashGapDateClusters}}{{{_integer(int(internal_wide['date_clusters']))}}}",
    ]
    for name, row in rows.items():
        effect, standard_error, unit = _effect(row)
        lines.append(
            f"\\newcommand{{\\VFourFlashGap{name}Coef}}{{{_signed(effect, unit)}}}"
        )
        lines.append(
            f"\\newcommand{{\\VFourFlashGap{name}SE}}{{{_unsigned(standard_error, unit)}}}"
        )
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_v4_flash_gap_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
