#!/usr/bin/env python3
"""Build deck macros for the V1 mandate and V2 voluntary-pairing comparison."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import DATA_DIR, OUTPUT_DIR
from ddvc.runtime import atomic_output


PROCESSED_DIR = DATA_DIR / "processed"
V1_CLASSES = PROCESSED_DIR / "v1_trade_classes_daily.parquet"
V2_ROUTING = PROCESSED_DIR / "v2_pair_routing_daily.parquet"
V2_FIRST_TRADE = PROCESSED_DIR / "v2_pair_first_trade.parquet"
DECK_VALUES = OUTPUT_DIR / "exhibits" / "v1_architecture_deck_values.tex"
WETH = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
DISPLAY_YEAR = 2026


def load_inputs(
    *,
    v1_classes_path: Path = V1_CLASSES,
    v2_routing_path: Path = V2_ROUTING,
    v2_first_trade_path: Path = V2_FIRST_TRADE,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Read only the columns and calendar slice used by the presentation."""

    start = pd.Timestamp(f"{DISPLAY_YEAR}-01-01")
    end = pd.Timestamp(f"{DISPLAY_YEAR + 1}-01-01")
    filters = [("date", ">=", start), ("date", "<", end)]
    v1 = pd.read_parquet(v1_classes_path, columns=["n_token_to_token"])
    routing = pd.read_parquet(
        v2_routing_path,
        columns=["t0", "t1", "kind", "n", "date"],
        filters=filters,
    )
    first_trade = pd.read_parquet(
        v2_first_trade_path,
        columns=["token0", "token1", "first_trade"],
        filters=[("first_trade", ">=", start), ("first_trade", "<", end)],
    )
    return v1, routing, first_trade


def render_v1_architecture_deck_values(
    v1_classes: pd.DataFrame,
    v2_routing: pd.DataFrame,
    v2_first_trade: pd.DataFrame,
) -> str:
    """Render the three displayed architecture facts from structured inputs."""

    required = {
        "v1 trade classes": (v1_classes, {"n_token_to_token"}),
        "v2 routing": (v2_routing, {"t0", "t1", "kind", "n"}),
        "v2 first trades": (v2_first_trade, {"token0", "token1"}),
    }
    for label, (frame, columns) in required.items():
        missing = sorted(columns - set(frame.columns))
        if missing:
            raise ValueError(f"{label} missing columns: {', '.join(missing)}")

    forced_routes = int(v1_classes["n_token_to_token"].sum())
    direct = v2_routing[v2_routing["kind"].eq("direct")].copy()
    if forced_routes <= 0 or direct.empty or v2_first_trade.empty:
        raise ValueError("architecture display inputs are empty")
    if (direct["n"] < 0).any():
        raise ValueError("v2 routing contains a negative trade count")

    direct_total = float(direct["n"].sum())
    if direct_total <= 0:
        raise ValueError("v2 routing has no direct trades")
    direct_weth = direct["t0"].eq(WETH) | direct["t1"].eq(WETH)
    weth_trade_share = float(direct.loc[direct_weth, "n"].sum()) / direct_total
    first_weth = v2_first_trade["token0"].eq(WETH) | v2_first_trade["token1"].eq(WETH)
    weth_new_pair_share = float(first_weth.mean())
    trade_share_text = f"{weth_trade_share:.1%}".replace("%", r"\%")
    new_pair_share_text = f"{weth_new_pair_share:.1%}".replace("%", r"\%")

    return "\n".join(
        [
            "% Generated by scripts/tabulate/build_v1_architecture_deck_values.py; do not edit.",
            f"\\newcommand{{\\VOneForcedRoutes}}{{{forced_routes:,}}}",
            f"\\newcommand{{\\VTwoWethTradeShare}}{{{trade_share_text}}}",
            f"\\newcommand{{\\VTwoWethNewPairShare}}{{{new_pair_share_text}}}",
            "",
        ]
    )


def run(
    *,
    v1_classes_path: Path = V1_CLASSES,
    v2_routing_path: Path = V2_ROUTING,
    v2_first_trade_path: Path = V2_FIRST_TRADE,
    output_path: Path = DECK_VALUES,
) -> int:
    frames = load_inputs(
        v1_classes_path=v1_classes_path,
        v2_routing_path=v2_routing_path,
        v2_first_trade_path=v2_first_trade_path,
    )
    rendered = render_v1_architecture_deck_values(*frames)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--v1-classes", type=Path, default=V1_CLASSES)
    parser.add_argument("--v2-routing", type=Path, default=V2_ROUTING)
    parser.add_argument("--v2-first-trade", type=Path, default=V2_FIRST_TRADE)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(
        v1_classes_path=args.v1_classes,
        v2_routing_path=args.v2_routing,
        v2_first_trade_path=args.v2_first_trade,
        output_path=args.output,
    )


if __name__ == "__main__":
    raise SystemExit(main())
