#!/usr/bin/env python3
"""Build paper/deck macros for local bridge-liquidity feedback screens."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/bridge_liquidity_feedback.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/bridge_liquidity_feedback_deck_values.tex"


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def _integer(value: float) -> str:
    return f"{value:,.0f}".replace(",", "{,}")


def _signed_decimal(value: float, decimals: int = 3) -> str:
    if abs(value) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$"
    return f"${value:+.{decimals}f}$"


def _unsigned_decimal(value: float, decimals: int = 3) -> str:
    return f"${value:.{decimals}f}$"


def _signed_pp(value: float, decimals: int = 2) -> str:
    return f"${100.0 * value:+.{decimals}f}$ pp"


def _unsigned_pp(value: float, decimals: int = 2) -> str:
    return f"${abs(100.0 * value):.{decimals}f}$ pp"


def render_bridge_liquidity_feedback_deck_values(estimates: pd.DataFrame) -> str:
    required = {"claim_status", "record_type"}
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"bridge-feedback exhibit lacks columns: {missing}")
    if not estimates["claim_status"].eq("provisional_exploratory").all():
        raise ValueError("bridge-feedback rows are not provisional_exploratory")

    support_30 = _single(
        estimates,
        record_type="bridge_liquidity_feedback_support",
        horizon_days=30,
    )
    support_120 = _single(
        estimates,
        record_type="bridge_liquidity_feedback_support",
        horizon_days=120,
    )
    route_to_depth_30 = _single(
        estimates,
        record_type="bridge_liquidity_feedback_regression",
        model_id="future_bridge_depth_growth",
        horizon_days=30,
        outcome="future_delta_log_bridge_min_capital",
        regressor="route_share_five",
    )
    route_to_depth_120 = _single(
        estimates,
        record_type="bridge_liquidity_feedback_regression",
        model_id="future_bridge_depth_growth",
        horizon_days=120,
        outcome="future_delta_log_bridge_min_capital",
        regressor="route_share_five",
    )
    depth_to_route_30 = _single(
        estimates,
        record_type="bridge_liquidity_feedback_regression",
        model_id="future_route_share_growth",
        horizon_days=30,
        outcome="future_delta_route_share_five",
        regressor="log_bridge_min_capital",
    )
    depth_to_route_120 = _single(
        estimates,
        record_type="bridge_liquidity_feedback_regression",
        model_id="future_route_share_growth",
        horizon_days=120,
        outcome="future_delta_route_share_five",
        regressor="log_bridge_min_capital",
    )
    if not (
        float(route_to_depth_30["coefficient"]) > 0
        and float(route_to_depth_30["p_value"]) < 0.01
        and float(route_to_depth_120["coefficient"]) > 0
        and float(route_to_depth_120["p_value"]) < 0.01
        and float(depth_to_route_30["coefficient"]) > 0
        and float(depth_to_route_30["p_value"]) < 0.01
        and float(depth_to_route_120["coefficient"]) > 0
        and float(depth_to_route_120["p_value"]) < 0.01
    ):
        raise ValueError("bridge-feedback pattern no longer holds")

    route_to_depth_30_effect = 0.1 * float(route_to_depth_30["coefficient"])
    route_to_depth_30_se = 0.1 * float(route_to_depth_30["standard_error"])
    route_to_depth_120_effect = 0.1 * float(route_to_depth_120["coefficient"])
    route_to_depth_120_se = 0.1 * float(route_to_depth_120["standard_error"])
    lines = [
        "% Generated by scripts/tabulate/build_bridge_liquidity_feedback_deck_values.py; do not edit.",
        f"\\newcommand{{\\BridgeFeedbackMonthRows}}{{{_integer(float(support_30['candidate_rows']))}}}",
        f"\\newcommand{{\\BridgeFeedbackLongRows}}{{{_integer(float(support_120['candidate_rows']))}}}",
        f"\\newcommand{{\\BridgeFeedbackLongPairs}}{{{_integer(float(support_120['ordered_pairs']))}}}",
        f"\\newcommand{{\\BridgeFeedbackRouteToDepthMonthLog}}{{{_signed_decimal(route_to_depth_30_effect)}}}",
        f"\\newcommand{{\\BridgeFeedbackRouteToDepthMonthLogSE}}{{{_unsigned_decimal(route_to_depth_30_se)}}}",
        f"\\newcommand{{\\BridgeFeedbackRouteToDepthLongLog}}{{{_signed_decimal(route_to_depth_120_effect)}}}",
        f"\\newcommand{{\\BridgeFeedbackRouteToDepthLongLogSE}}{{{_unsigned_decimal(route_to_depth_120_se)}}}",
        f"\\newcommand{{\\BridgeFeedbackDepthToRouteMonthCoef}}{{{_signed_pp(float(depth_to_route_30['coefficient']))}}}",
        f"\\newcommand{{\\BridgeFeedbackDepthToRouteMonthSE}}{{{_unsigned_pp(float(depth_to_route_30['standard_error']))}}}",
        f"\\newcommand{{\\BridgeFeedbackDepthToRouteLongCoef}}{{{_signed_pp(float(depth_to_route_120['coefficient']))}}}",
        f"\\newcommand{{\\BridgeFeedbackDepthToRouteLongSE}}{{{_unsigned_pp(float(depth_to_route_120['standard_error']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(
    *,
    estimates_path: Path = ESTIMATES,
    output_path: Path = DECK_VALUES,
) -> int:
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_bridge_liquidity_feedback_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
