#!/usr/bin/env python3
"""Build presentation macros from the vehicle-formation exploration exhibit."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/vehicle_formation_exploration.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/vehicle_formation_deck_values.tex"
CODE_SOURCES = ["scripts/tabulate/build_vehicle_formation_deck_values.py"]


def _pct(value: float, decimals: int = 1) -> str:
    return f"{100 * value:.{decimals}f}\\%"


def _signed_pp(value: float, decimals: int = 1) -> str:
    points = 100 * value
    if abs(points) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$ pp"
    return f"${points:+.{decimals}f}$ pp"


def _unsigned_pp(value: float, decimals: int = 1) -> str:
    return f"${100 * value:.{decimals}f}$ pp"


def _int(value: int | float) -> str:
    return f"{int(value):,}".replace(",", "{,}")


def _one(frame: pd.DataFrame, **selectors: object) -> pd.Series:
    selected = frame.copy()
    for column, value in selectors.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one formation row for {selectors}; found {len(selected)}")
    return selected.iloc[0]


def render_vehicle_formation_deck_values(estimates: pd.DataFrame) -> str:
    required = {"record_type", "entry_year", "stable_share", "primary_routes"}
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"formation exhibit missing columns: {', '.join(missing)}")
    cohort_2024 = _one(estimates, record_type="entry_cohort", entry_year=2024)
    cohort_2026 = _one(estimates, record_type="entry_cohort", entry_year=2026)
    native_2026_30 = _one(
        estimates,
        record_type="entry_persistence",
        horizon_days=30,
        entry_year=2026,
        entry_type="native_only_entry",
    )
    stable_2026_30 = _one(
        estimates,
        record_type="entry_persistence",
        horizon_days=30,
        entry_year=2026,
        entry_type="stable_dominant_entry",
    )
    contrast_2026_30 = _one(
        estimates,
        record_type="entry_persistence_contrast",
        horizon_days=30,
        entry_year=2026,
    )
    stable_2024_120 = _one(
        estimates,
        record_type="entry_persistence",
        horizon_days=120,
        entry_year=2024,
        entry_type="stable_dominant_entry",
    )
    stable_2026_120 = _one(
        estimates,
        record_type="entry_persistence",
        horizon_days=120,
        entry_year=2026,
        entry_type="stable_dominant_entry",
    )
    non_weth_2024 = _one(
        estimates,
        record_type="entry_endpoint_class",
        entry_year=2024,
        endpoint_class="non_weth_endpoint",
    )
    non_weth_2026 = _one(
        estimates,
        record_type="entry_endpoint_class",
        entry_year=2026,
        endpoint_class="non_weth_endpoint",
    )
    weth_2026 = _one(
        estimates,
        record_type="entry_endpoint_class",
        entry_year=2026,
        endpoint_class="weth_endpoint",
    )
    values = [
        float(cohort_2024["stable_share"]),
        float(cohort_2026["stable_share"]),
        float(native_2026_30["stable_share"]),
        float(stable_2026_30["stable_share"]),
        float(contrast_2026_30["coefficient"]),
        float(contrast_2026_30["standard_error"]),
        float(stable_2024_120["stable_share"]),
        float(stable_2026_120["stable_share"]),
        float(non_weth_2024["stable_share"]),
        float(non_weth_2026["stable_share"]),
        float(weth_2026["route_mass_share"]),
    ]
    if not all(math.isfinite(value) for value in values):
        raise ValueError("formation deck values contain nonfinite cells")
    if not float(non_weth_2026["stable_share"]) > float(non_weth_2024["stable_share"]):
        raise ValueError("non-WETH entry stable share no longer rises")
    lines = [
        "% Generated by scripts/tabulate/build_vehicle_formation_deck_values.py; do not edit.",
        f"\\newcommand{{\\FormationEntryStableShareBase}}{{{_pct(float(cohort_2024['stable_share']))}}}",
        f"\\newcommand{{\\FormationEntryStableShareEnd}}{{{_pct(float(cohort_2026['stable_share']))}}}",
        f"\\newcommand{{\\FormationEntryPairsEnd}}{{{_int(cohort_2026['pairs'])}}}",
        f"\\newcommand{{\\FormationThirtyNativeBirthStableShare}}{{{_pct(float(native_2026_30['stable_share']))}}}",
        f"\\newcommand{{\\FormationThirtyStableBirthStableShare}}{{{_pct(float(stable_2026_30['stable_share']))}}}",
        f"\\newcommand{{\\FormationThirtyStableBirthPairs}}{{{_int(stable_2026_30['pairs'])}}}",
        f"\\newcommand{{\\FormationThirtyPersistenceGap}}{{{_signed_pp(float(contrast_2026_30['coefficient']))}}}",
        f"\\newcommand{{\\FormationThirtyPersistenceSE}}{{{_unsigned_pp(float(contrast_2026_30['standard_error']))}}}",
        f"\\newcommand{{\\FormationStableBirthShareOneTwentyBase}}{{{_pct(float(stable_2024_120['stable_share']))}}}",
        f"\\newcommand{{\\FormationStableBirthShareOneTwentyEnd}}{{{_pct(float(stable_2026_120['stable_share']))}}}",
        f"\\newcommand{{\\FormationNonWethEntryStableShareBase}}{{{_pct(float(non_weth_2024['stable_share']))}}}",
        f"\\newcommand{{\\FormationNonWethEntryStableShareEnd}}{{{_pct(float(non_weth_2026['stable_share']))}}}",
        f"\\newcommand{{\\FormationWethEntryRouteMassEnd}}{{{_pct(float(weth_2026['route_mass_share']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_vehicle_formation_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
