#!/usr/bin/env python3
"""Build paper/deck macros for V4 transaction-origin participation timing."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/v4_lp_origin_timing.jsonl"
OUTPUT = OUTPUT_DIR / "exhibits/v4_lp_origin_timing_deck_values.tex"
PRIMARY_SAMPLE = "primary_nonzero_180"


def _single(estimates: pd.DataFrame, *, outcome: str) -> pd.Series:
    selected = estimates[
        estimates["sample_variant"].eq(PRIMARY_SAMPLE)
        & estimates["predictor"].eq("internal_tx_share")
        & estimates["outcome"].eq(outcome)
    ]
    if len(selected) != 1:
        raise ValueError(f"expected one internal-routing row for {outcome}")
    return selected.iloc[0]


def _stars(value: float) -> str:
    if value < 0.01:
        return "^{***}"
    if value < 0.05:
        return "^{**}"
    if value < 0.10:
        return "^{*}"
    return ""


def _estimate(row: pd.Series) -> str:
    return (
        f"${float(row['effect_per_10pp_predictor']):+.3f}"
        f"{_stars(float(row['holm_p_value']))}$"
    )


def _se(row: pd.Series) -> str:
    return f"${float(row['standard_error_per_10pp_predictor']):.3f}$"


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def render_v4_lp_origin_timing_deck_values(estimates: pd.DataFrame) -> str:
    required = {
        "sample_variant",
        "predictor",
        "outcome",
        "effect_per_10pp_predictor",
        "standard_error_per_10pp_predictor",
        "holm_p_value",
        "n_observations",
        "date_clusters",
    }
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"V4 origin-timing estimates lack columns: {missing}")
    near_incumbent = _single(
        estimates, outcome="near_log1p_incumbent_actions"
    )
    late_entry = _single(
        estimates, outcome="late_log1p_first_active_origins"
    )
    late_incumbent = _single(
        estimates, outcome="late_log1p_incumbent_actions"
    )
    rows = (near_incumbent, late_entry, late_incumbent)
    if not all(float(row["effect_per_10pp_predictor"]) > 0 for row in rows):
        raise ValueError("V4 origin-timing direction no longer supports the headline")
    if not all(float(row["holm_p_value"]) < 0.01 for row in rows):
        raise ValueError("V4 origin-timing headline no longer survives Holm control")
    if len({int(row["n_observations"]) for row in rows}) != 1:
        raise ValueError("V4 origin-timing headline rows mix samples")
    if len({int(row["date_clusters"]) for row in rows}) != 1:
        raise ValueError("V4 origin-timing headline rows mix cluster counts")
    lines = [
        "% Generated by scripts/tabulate/build_v4_lp_origin_timing_deck_values.py; do not edit.",
        f"\\newcommand{{\\VFourOriginTimingRows}}{{{_integer(int(near_incumbent['n_observations']))}}}",
        f"\\newcommand{{\\VFourOriginTimingClusters}}{{{_integer(int(near_incumbent['date_clusters']))}}}",
        f"\\newcommand{{\\VFourOriginNearIncumbentCoef}}{{{_estimate(near_incumbent)}}}",
        f"\\newcommand{{\\VFourOriginNearIncumbentSE}}{{{_se(near_incumbent)}}}",
        f"\\newcommand{{\\VFourOriginLateEntryCoef}}{{{_estimate(late_entry)}}}",
        f"\\newcommand{{\\VFourOriginLateEntrySE}}{{{_se(late_entry)}}}",
        f"\\newcommand{{\\VFourOriginLateIncumbentCoef}}{{{_estimate(late_incumbent)}}}",
        f"\\newcommand{{\\VFourOriginLateIncumbentSE}}{{{_se(late_incumbent)}}}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    rendered = render_v4_lp_origin_timing_deck_values(
        pd.read_json(args.input, lines=True)
    )
    with atomic_output(args.output) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
