#!/usr/bin/env python3
"""Build paper and presentation macros for endpoint-direction contributions."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.runtime import atomic_output


RESULTS = OUTPUT_DIR / "exhibits/endpoint_direction_decomposition.jsonl"
VALUES = OUTPUT_DIR / "exhibits/endpoint_direction_deck_values.tex"


def _signed_pp(value: float) -> str:
    return f"${100.0 * value:+.1f}$ pp"


def _number_pp(value: float) -> str:
    return f"{100.0 * value:.1f}"


def _percent(value: float) -> str:
    return f"{100.0 * value:.1f}\\%"


def render_endpoint_direction_values(results: pd.DataFrame) -> str:
    """Render the three economically distinct endpoint channels."""

    required = {
        "metric",
        "endpoint_group",
        "common_calendar_days",
        "stable_share_contribution_change",
        "share_of_total_stable_change",
        "overall_stable_share_baseline",
        "overall_stable_share_comparison",
        "overall_stable_share_change",
    }
    missing = sorted(required - set(results.columns))
    if missing:
        raise ValueError(f"endpoint-direction results lack columns: {missing}")
    if set(results["common_calendar_days"]) != {181}:
        raise ValueError("endpoint-direction presentation requires 181 common days")

    def rows(metric: str, groups: tuple[str, ...]) -> pd.DataFrame:
        selected = results[
            results["metric"].eq(metric) & results["endpoint_group"].isin(groups)
        ]
        if set(selected["endpoint_group"]) != set(groups) or len(selected) != len(groups):
            raise ValueError(f"expected one {metric} row for {groups}")
        return selected

    channels = (
        ("Other", ("other_endpoints",)),
        ("NativeStable", ("native_to_stable", "stable_to_native")),
        ("StableStable", ("stable_to_stable",)),
    )
    lines = [
        "% Generated by scripts/tabulate/build_endpoint_direction_deck_values.py; do not edit.",
        "% Exact common-calendar endpoint-direction contributions to the headline stable-share change.",
    ]
    for macro_metric, metric in (
        ("Count", "count_share"),
        ("Value", "strict_intermediation_value_share"),
    ):
        metric_rows = results[results["metric"].eq(metric)]
        if len(metric_rows) != 5:
            raise ValueError(f"expected five endpoint groups for {metric}")
        overall_columns = (
            "overall_stable_share_baseline",
            "overall_stable_share_comparison",
            "overall_stable_share_change",
        )
        if any(metric_rows[column].nunique() != 1 for column in overall_columns):
            raise ValueError(f"{metric} overall estimates are not invariant")
        first = metric_rows.iloc[0]
        lines.extend(
            [
                f"\\newcommand{{\\Endpoint{macro_metric}Base}}{{{_percent(float(first['overall_stable_share_baseline']))}}}",
                f"\\newcommand{{\\Endpoint{macro_metric}End}}{{{_percent(float(first['overall_stable_share_comparison']))}}}",
                f"\\newcommand{{\\Endpoint{macro_metric}Change}}{{{_signed_pp(float(first['overall_stable_share_change']))}}}",
                f"\\newcommand{{\\Endpoint{macro_metric}ChangeNumber}}{{{_number_pp(float(first['overall_stable_share_change']))}}}",
            ]
        )
        channel_change_sum = 0.0
        for macro_group, groups in channels:
            selected = rows(metric, groups)
            change = float(selected["stable_share_contribution_change"].sum())
            share = float(selected["share_of_total_stable_change"].sum())
            channel_change_sum += change
            lines.extend(
                [
                    f"\\newcommand{{\\Endpoint{macro_group}{macro_metric}Contribution}}{{{_signed_pp(change)}}}",
                    f"\\newcommand{{\\Endpoint{macro_group}{macro_metric}ContributionNumber}}{{{_number_pp(change)}}}",
                    f"\\newcommand{{\\Endpoint{macro_group}{macro_metric}Share}}{{{_percent(share)}}}",
                ]
            )
        native_native = rows(metric, ("native_to_native",))
        native_native_change = float(
            native_native["stable_share_contribution_change"].iloc[0]
        )
        if not np.isclose(
            channel_change_sum + native_native_change,
            float(first["overall_stable_share_change"]),
            atol=1e-10,
        ):
            raise ValueError(f"{metric} presentation channels do not reconcile")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=RESULTS)
    parser.add_argument("--values", type=Path, default=VALUES)
    args = parser.parse_args()
    results = pd.read_json(args.results, lines=True)
    rendered = render_endpoint_direction_values(results)
    with atomic_output(args.values) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
