#!/usr/bin/env python3
"""Build generated deck macros for the bridge divergence-risk boundary test."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


MODELS = OUTPUT_DIR / "exhibits" / "bridge_lp_divergence_risk_models.jsonl"
SUPPORT = OUTPUT_DIR / "exhibits" / "bridge_lp_divergence_risk_support.jsonl"
VALUES = OUTPUT_DIR / "exhibits" / "bridge_lp_divergence_risk_deck_values.tex"


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        if column not in selected.columns:
            raise ValueError(f"bridge-risk data lack selector column {column}")
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def _signed(value: float, digits: int = 3) -> str:
    return f"${value:+.{digits}f}$"


def _unsigned(value: float, digits: int = 3) -> str:
    return f"${value:.{digits}f}$"


def _pct(value: float) -> str:
    return f"{100.0 * value:.1f}\\%"


def _integer(value: object) -> str:
    return f"{int(round(float(value))):,}".replace(",", "{,}")


def render_bridge_lp_divergence_risk_deck_values(
    models: pd.DataFrame,
    support: pd.DataFrame,
) -> str:
    current = _single(
        models,
        record_type="bridge_lp_divergence_risk_model_coefficient",
        model_id="m1_prior_depth_volatility",
        predictor="bridge_relative_volatility",
    )
    future = _single(
        models,
        record_type="bridge_lp_divergence_risk_model_coefficient",
        model_id="m3_future_depth_volatility",
        predictor="bridge_relative_volatility",
    )
    sample = _single(
        support,
        record_type="bridge_lp_divergence_risk_sample",
    )

    numeric = {
        "current effect": current["effect_log_points_per_10pp_volatility"],
        "current standard error": current[
            "standard_error_log_points_per_10pp_volatility"
        ],
        "future effect": future["effect_log_points_per_10pp_volatility"],
        "future standard error": future[
            "standard_error_log_points_per_10pp_volatility"
        ],
        "observations": current["observations"],
        "pair clusters": current["endpoint_pair_clusters"],
        "date clusters": current["anchor_date_clusters"],
        "native median": sample["median_native_bridge_relative_volatility"],
        "stable median": sample["median_stable_bridge_relative_volatility"],
        "stable lower-risk share": sample[
            "share_pair_dates_stable_relative_volatility_lower"
        ],
    }
    for label, value in numeric.items():
        if not math.isfinite(float(value)):
            raise ValueError(f"bridge-risk macro source has non-finite {label}")
    if not (
        float(current["effect_log_points_per_10pp_volatility"]) < 0
        and float(future["effect_log_points_per_10pp_volatility"]) < 0
        and float(current["standard_error_log_points_per_10pp_volatility"]) > 0
        and float(future["standard_error_log_points_per_10pp_volatility"]) > 0
    ):
        raise ValueError("bridge-risk coefficient direction or uncertainty changed")
    if not (
        float(sample["median_stable_bridge_relative_volatility"])
        > float(sample["median_native_bridge_relative_volatility"])
        and 0
        <= float(sample["share_pair_dates_stable_relative_volatility_lower"])
        <= 1
    ):
        raise ValueError("bridge-risk family comparison changed or is invalid")
    if not (
        int(current["observations"]) == int(future["observations"])
        and int(current["endpoint_pair_clusters"])
        == int(future["endpoint_pair_clusters"])
        and int(current["anchor_date_clusters"])
        == int(future["anchor_date_clusters"])
    ):
        raise ValueError("bridge-risk regressions use inconsistent support")

    lines = [
        "% Generated by scripts/tabulate/build_bridge_lp_divergence_risk_deck_values.py; do not edit.",
        f"\\newcommand{{\\BridgeRiskCurrentVolEffect}}{{{_signed(float(current['effect_log_points_per_10pp_volatility']))}}}",
        f"\\newcommand{{\\BridgeRiskCurrentVolSE}}{{{_unsigned(float(current['standard_error_log_points_per_10pp_volatility']))}}}",
        f"\\newcommand{{\\BridgeRiskFutureVolEffect}}{{{_signed(float(future['effect_log_points_per_10pp_volatility']))}}}",
        f"\\newcommand{{\\BridgeRiskFutureVolSE}}{{{_unsigned(float(future['standard_error_log_points_per_10pp_volatility']))}}}",
        f"\\newcommand{{\\BridgeRiskNativeMedianVol}}{{{_pct(float(sample['median_native_bridge_relative_volatility']))}}}",
        f"\\newcommand{{\\BridgeRiskStableMedianVol}}{{{_pct(float(sample['median_stable_bridge_relative_volatility']))}}}",
        f"\\newcommand{{\\BridgeRiskStableLowerShare}}{{{_pct(float(sample['share_pair_dates_stable_relative_volatility_lower']))}}}",
        f"\\newcommand{{\\BridgeRiskObservations}}{{{_integer(current['observations'])}}}",
        f"\\newcommand{{\\BridgeRiskPairClusters}}{{{_integer(current['endpoint_pair_clusters'])}}}",
        f"\\newcommand{{\\BridgeRiskDateClusters}}{{{_integer(current['anchor_date_clusters'])}}}",
    ]
    return "\n".join(lines) + "\n"


def run(
    *,
    models_path: Path = MODELS,
    support_path: Path = SUPPORT,
    output_path: Path = VALUES,
) -> int:
    for path in (models_path, support_path):
        require_presentation_source(path)
    rendered = render_bridge_lp_divergence_risk_deck_values(
        pd.read_json(models_path, lines=True),
        pd.read_json(support_path, lines=True),
    )
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--models", type=Path, default=MODELS)
    parser.add_argument("--support", type=Path, default=SUPPORT)
    parser.add_argument("--output", type=Path, default=VALUES)
    args = parser.parse_args()
    return run(
        models_path=args.models,
        support_path=args.support,
        output_path=args.output,
    )


if __name__ == "__main__":
    raise SystemExit(main())
