#!/usr/bin/env python3
"""Build deck macros from the V4 flash-accounting LP mechanism exhibit."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_presentation_source
from ddvc.runtime import atomic_output


ESTIMATES = OUTPUT_DIR / "exhibits/v4_flash_lp_mechanism_exploration.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/v4_flash_lp_deck_values.tex"
HORIZON_DAYS = 120


def _signed_pp(value: float, decimals: int = 2) -> str:
    points = 100 * value
    if abs(points) < 0.5 * 10 ** (-decimals):
        return f"${0:.{decimals}f}$ pp"
    return f"${points:+.{decimals}f}$ pp"


def _unsigned_pp(value: float, decimals: int = 2) -> str:
    return f"${100 * value:.{decimals}f}$ pp"


def _integer(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def _single(frame: pd.DataFrame, **conditions: object) -> pd.Series:
    selected = frame
    for column, value in conditions.items():
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {conditions}; found {len(selected)}")
    return selected.iloc[0]


def _row(
    estimates: pd.DataFrame,
    *,
    predictor: str,
    outcome: str,
) -> pd.Series:
    return _single(
        estimates,
        horizon_days=HORIZON_DAYS,
        predictor=predictor,
        outcome=outcome,
    )


def render_v4_flash_lp_deck_values(estimates: pd.DataFrame) -> str:
    required = {
        "analysis_status",
        "record_type",
        "horizon_days",
        "predictor",
        "outcome",
        "effect_per_10pp_predictor",
        "standard_error",
        "p_value",
        "n_observations",
        "date_clusters",
    }
    missing = sorted(required - set(estimates.columns))
    if missing:
        raise ValueError(f"V4 flash-LP exhibit missing columns: {missing}")
    if not estimates["analysis_status"].eq("exploratory_mechanism").all():
        raise ValueError("V4 flash-LP rows are not labelled exploratory_mechanism")
    internal_narrow = _row(
        estimates,
        predictor="internal_tx_share",
        outcome="future_narrow_medium_action_share",
    )
    internal_wide = _row(
        estimates,
        predictor="internal_tx_share",
        outcome="future_wide_very_wide_action_share",
    )
    multileg_narrow = _row(
        estimates,
        predictor="multi_leg_tx_share",
        outcome="future_narrow_medium_action_share",
    )
    multileg_wide = _row(
        estimates,
        predictor="multi_leg_tx_share",
        outcome="future_wide_very_wide_action_share",
    )
    if not (
        float(internal_narrow["effect_per_10pp_predictor"]) < 0
        and float(internal_wide["effect_per_10pp_predictor"]) > 0
        and float(multileg_narrow["effect_per_10pp_predictor"]) < 0
        and float(multileg_wide["effect_per_10pp_predictor"]) > 0
        and float(internal_narrow["p_value"]) < 0.01
        and float(internal_wide["p_value"]) < 0.01
        and float(multileg_narrow["p_value"]) < 0.01
        and float(multileg_wide["p_value"]) < 0.01
        and int(internal_wide["n_observations"]) > 1_000
    ):
        raise ValueError("V4 flash-LP range-allocation headline no longer holds")
    lines = [
        "% Generated by scripts/tabulate/build_v4_flash_lp_deck_values.py; do not edit.",
        f"\\newcommand{{\\VFourFlashLpRows}}{{{_integer(int(internal_wide['n_observations']))}}}",
        f"\\newcommand{{\\VFourFlashLpDateClusters}}{{{_integer(int(internal_wide['date_clusters']))}}}",
        f"\\newcommand{{\\VFourFlashInternalNarrowLongCoef}}{{{_signed_pp(float(internal_narrow['effect_per_10pp_predictor']))}}}",
        f"\\newcommand{{\\VFourFlashInternalNarrowLongSE}}{{{_unsigned_pp(0.1 * float(internal_narrow['standard_error']))}}}",
        f"\\newcommand{{\\VFourFlashInternalWideLongCoef}}{{{_signed_pp(float(internal_wide['effect_per_10pp_predictor']))}}}",
        f"\\newcommand{{\\VFourFlashInternalWideLongSE}}{{{_unsigned_pp(0.1 * float(internal_wide['standard_error']))}}}",
        f"\\newcommand{{\\VFourFlashMultilegNarrowLongCoef}}{{{_signed_pp(float(multileg_narrow['effect_per_10pp_predictor']))}}}",
        f"\\newcommand{{\\VFourFlashMultilegNarrowLongSE}}{{{_unsigned_pp(0.1 * float(multileg_narrow['standard_error']))}}}",
        f"\\newcommand{{\\VFourFlashMultilegWideLongCoef}}{{{_signed_pp(float(multileg_wide['effect_per_10pp_predictor']))}}}",
        f"\\newcommand{{\\VFourFlashMultilegWideLongSE}}{{{_unsigned_pp(0.1 * float(multileg_wide['standard_error']))}}}",
    ]
    return "\n".join(lines) + "\n"


def run(*, estimates_path: Path = ESTIMATES, output_path: Path = DECK_VALUES) -> int:
    require_presentation_source(estimates_path)
    estimates = pd.read_json(estimates_path, lines=True)
    rendered = render_v4_flash_lp_deck_values(estimates)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--estimates", type=Path, default=ESTIMATES)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(estimates_path=args.estimates, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
