#!/usr/bin/env python3
"""Render Table 0: variable notation and construction.

One script owns exactly one exhibit. This table is the public-facing data
dictionary for the observations table used by summary statistics, regressions,
and exploratory plots.
"""

from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ddvc.variable_registry import specs_by_group  # noqa: E402


OUT_TEX = ROOT / "output" / "tables" / "table_00_variable_notation.tex"


def _latex_escape(value: object) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def _tt(value: str) -> str:
    parts = [_latex_escape(part) for part in value.split("_")]
    return r"\texttt{" + r"\_\allowbreak{}".join(parts) + "}"


def render_latex() -> str:
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\caption{Variable notation and construction}",
        r"\label{tab:variable-notation}",
        r"\scriptsize",
        r"\begin{tabular}{@{}p{0.17\linewidth}p{0.18\linewidth}p{0.18\linewidth}p{0.39\linewidth}@{}}",
        r"\toprule",
        r"Notation & Observation-table column & Unit & Construction \\",
        r"\midrule",
    ]
    first_group = True
    for group, specs in specs_by_group().items():
        if not first_group:
            lines.append(r"\addlinespace")
        first_group = False
        lines.append(rf"\multicolumn{{4}}{{l}}{{\textit{{{_latex_escape(group)}}}}} \\")
        for spec in specs:
            lines.append(
                " & ".join(
                    [
                        spec.notation,
                        _tt(spec.column),
                        _latex_escape(spec.unit),
                        _latex_escape(spec.construction),
                    ]
                )
                + r" \\"
            )
    note = (
        "Notes: This table defines the notation and implemented columns used to construct the "
        "canonical observations table. The observations table is generated by "
        "\\texttt{scripts/process/build\\_observations\\_table.py} and is the input to "
        "summary statistics, regressions, and exploratory figures."
    )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\vspace{0.35em}",
            r"\begin{minipage}{0.98\linewidth}",
            rf"\footnotesize {note}",
            r"\end{minipage}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(render_latex(), encoding="utf-8")
    print(f"wrote {OUT_TEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
