#!/usr/bin/env python3
"""Direct runner for Table 0: variable notation and construction."""

from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
TABULATE = ROOT / "scripts" / "tabulate"
for path in (SRC, TABULATE):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from ddvc.variable_registry import specs_by_group  # noqa: E402
from utils import write_table_artifacts  # noqa: E402


def latex_escape(value: object) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def latex_texttt_breakable(value: str) -> str:
    parts = [latex_escape(part) for part in value.split("_")]
    return r"\texttt{" + r"\_\allowbreak{}".join(parts) + "}"


lines = [
    r"\begin{table}[!htbp]",
    r"\centering",
    r"\caption{Variable notation and construction}",
    r"\label{tab:variable-notation}",
    r"\scriptsize",
    r"\begin{tabular}{@{}p{0.17\linewidth}p{0.18\linewidth}p{0.18\linewidth}p{0.39\linewidth}@{}}",
    r"\toprule",
    r"Notation & Observation-table column & Unit & Construction \\",
    r"\midrule",
]
first_group = True
for group, specs in specs_by_group().items():
    if not first_group:
        lines.append(r"\addlinespace")
    first_group = False
    lines.append(rf"\multicolumn{{4}}{{l}}{{\textit{{{latex_escape(group)}}}}} \\")
    for spec in specs:
        lines.append(
            " & ".join(
                [
                    spec.notation,
                    latex_texttt_breakable(spec.column),
                    latex_escape(spec.unit),
                    latex_escape(spec.construction),
                ]
            )
            + r" \\"
        )
note = (
    "Notes: This table defines the notation and implemented columns used to construct the "
    "canonical observations table. The observations table is generated by "
    "\\texttt{scripts/process/build\\_observations\\_table.py} and is the input to "
    "summary statistics, regressions, and exploratory figures."
)
lines.extend(
    [
        r"\bottomrule",
        r"\end{tabular}",
        r"\vspace{0.35em}",
        r"\begin{minipage}{0.98\linewidth}",
        rf"\footnotesize {note}",
        r"\end{minipage}",
        r"\end{table}",
    ]
)

out_tex, out_pdf = write_table_artifacts("table_00_variable_notation", "\n".join(lines) + "\n")
print(f"wrote {out_tex.relative_to(ROOT)}")
print(f"wrote {out_pdf.relative_to(ROOT)}")
