#!/usr/bin/env python3
"""Render all-route participation and atomic-pair network position."""

from __future__ import annotations

import pandas as pd

from ddvc.paper_tables import write_table_artifacts
from ddvc.paths import OUTPUT_DIR
from ddvc.runtime import atomic_output


COMPOSITION = OUTPUT_DIR / "exhibits/intermediation_by_type.jsonl"
NETWORK = OUTPUT_DIR / "exhibits/network_betweenness.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits/network_position_deck_values.tex"
YEARS = (2020, 2024, 2026)
TOKENS = ("WETH", "USDC", "USDT")


def _one(frame: pd.DataFrame, **selectors: object) -> pd.Series:
    selected = frame.copy()
    for column, value in selectors.items():
        if column not in selected:
            raise ValueError(f"input lacks selector column: {column}")
        selected = selected[selected[column].eq(value)]
    if len(selected) != 1:
        raise ValueError(f"expected one row for {selectors}, found {len(selected)}")
    return selected.iloc[0]


def _pct(value: object) -> str:
    return f"{100 * float(value):.1f}"


def _pct_macro(value: object) -> str:
    return _pct(value) + r"\%"


def render_table(composition: pd.DataFrame, network: pd.DataFrame) -> str:
    rows = [
        r"\begin{tabularx}{\linewidth}{@{}ll>{\raggedleft\arraybackslash}X>{\raggedleft\arraybackslash}X>{\raggedleft\arraybackslash}X@{}}",
        r"\toprule",
        r"\multicolumn{5}{@{}l}{\textit{Panel A. All complete route lengths}} \\",
        r"Year & Currency family & Intermediary-position share [\%] & Route-participation share [\%] & Routes using family \\",
        r"\midrule",
    ]
    for year in YEARS:
        year_label = "2026 H1" if year == 2026 else str(year)
        for asset_type, label in (("native", "Native"), ("stable", "Stablecoin")):
            result = _one(
                composition,
                year=year,
                integration_scope="all",
                asset_type=asset_type,
            )
            rows.append(
                f"{year_label} & {label} & {_pct(result['episode_share'])} & "
                f"{_pct(result['route_participation_share'])} & "
                f"{int(result['route_count']):,} \\\\"
            )
            year_label = ""

    rows.extend(
        [
            r"\addlinespace[0.6em]",
            r"\multicolumn{5}{@{}l}{\textit{Panel B. Named currencies in the atomic-pair graph}} \\",
            r"Currency & Year & Betweenness (rank) & Intermediary-position share [\%] & Route-participation share [\%] \\",
            r"\midrule",
        ]
    )
    for symbol in TOKENS:
        display_symbol = symbol
        for year in YEARS:
            result = _one(network, year=year, symbol=symbol)
            year_label = "2026 H1" if year == 2026 else str(year)
            rows.append(
                f"{display_symbol} & {year_label} & {float(result['betweenness']):.3f} "
                f"({int(result['betweenness_rank'])}) & "
                f"{_pct(result['intermediary_position_share'])} & "
                f"{_pct(result['route_participation_share'])} \\\\"
            )
            display_symbol = ""
    rows.extend([r"\bottomrule", r"\end{tabularx}", ""])
    return "\n".join(rows)


def render_deck_values(composition: pd.DataFrame, network: pd.DataFrame) -> str:
    weth_2024 = _one(network, year=2024, symbol="WETH")
    weth_2026 = _one(network, year=2026, symbol="WETH")
    usdc_2024 = _one(network, year=2024, symbol="USDC")
    usdc_2026 = _one(network, year=2026, symbol="USDC")
    usdt_2024 = _one(network, year=2024, symbol="USDT")
    usdt_2026 = _one(network, year=2026, symbol="USDT")
    stable_2024 = _one(
        composition,
        year=2024,
        integration_scope="all",
        asset_type="stable",
    )
    stable_2026 = _one(
        composition,
        year=2026,
        integration_scope="all",
        asset_type="stable",
    )
    rank_years = int(
        network.loc[network["symbol"].eq("WETH"), "year"].nunique()
    )
    if not network.loc[network["symbol"].eq("WETH"), "betweenness_rank"].eq(1).all():
        raise ValueError("WETH is not first in betweenness in every year")
    return "\n".join(
        [
            "% Generated by scripts/tabulate/render_network_position.py; do not edit.",
            f"\\newcommand{{\\NetworkWethBetweennessTwentySix}}{{{float(weth_2026['betweenness']):.3f}}}",
            f"\\newcommand{{\\NetworkWethRankYears}}{{{rank_years}}}",
            f"\\newcommand{{\\NetworkWethPositionTwentyFour}}{{{_pct_macro(weth_2024['intermediary_position_share'])}}}",
            f"\\newcommand{{\\NetworkWethPositionTwentySix}}{{{_pct_macro(weth_2026['intermediary_position_share'])}}}",
            f"\\newcommand{{\\NetworkStableDuoPositionTwentyFour}}{{{_pct_macro(float(usdc_2024['intermediary_position_share']) + float(usdt_2024['intermediary_position_share']))}}}",
            f"\\newcommand{{\\NetworkStableDuoPositionTwentySix}}{{{_pct_macro(float(usdc_2026['intermediary_position_share']) + float(usdt_2026['intermediary_position_share']))}}}",
            f"\\newcommand{{\\NetworkStableParticipationTwentyFour}}{{{_pct_macro(stable_2024['route_participation_share'])}}}",
            f"\\newcommand{{\\NetworkStableParticipationTwentySix}}{{{_pct_macro(stable_2026['route_participation_share'])}}}",
            "",
        ]
    )


def main() -> int:
    composition = pd.read_json(COMPOSITION, lines=True)
    network = pd.read_json(NETWORK, lines=True)
    write_table_artifacts(
        "network_position",
        render_table(composition, network),
        preview_width="8.2in",
    )
    with atomic_output(DECK_VALUES) as temporary:
        temporary.write_text(
            render_deck_values(composition, network), encoding="utf-8"
        )
    print(f"wrote {DECK_VALUES}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
