from __future__ import annotations

import pandas as pd

from scripts.tabulate.build_vehicle_formation_deck_values import (
    render_vehicle_formation_deck_values,
)


def test_vehicle_formation_deck_values_render_key_macros() -> None:
    estimates = pd.DataFrame(
        [
            {
                "record_type": "entry_cohort",
                "entry_year": 2024,
                "pairs": 10,
                "primary_routes": 100,
                "stable_share": 0.05,
            },
            {
                "record_type": "entry_cohort",
                "entry_year": 2026,
                "pairs": 20,
                "primary_routes": 200,
                "stable_share": 0.25,
            },
            {
                "record_type": "entry_persistence",
                "horizon_days": 30,
                "entry_year": 2026,
                "entry_type": "native_only_entry",
                "pairs": 18,
                "primary_routes": 180,
                "stable_share": 0.005,
            },
            {
                "record_type": "entry_persistence",
                "horizon_days": 30,
                "entry_year": 2026,
                "entry_type": "stable_dominant_entry",
                "pairs": 2,
                "primary_routes": 20,
                "stable_share": 0.975,
            },
            {
                "record_type": "entry_persistence_contrast",
                "horizon_days": 30,
                "entry_year": 2026,
                "primary_routes": 200,
                "stable_share": None,
                "coefficient": 0.97,
                "standard_error": 0.02,
            },
            {
                "record_type": "entry_persistence",
                "horizon_days": 120,
                "entry_year": 2024,
                "entry_type": "stable_dominant_entry",
                "pairs": 2,
                "primary_routes": 20,
                "stable_share": 0.98,
            },
            {
                "record_type": "entry_persistence",
                "horizon_days": 120,
                "entry_year": 2026,
                "entry_type": "stable_dominant_entry",
                "pairs": 2,
                "primary_routes": 20,
                "stable_share": 0.99,
            },
            {
                "record_type": "entry_persistence_contrast",
                "horizon_days": 120,
                "entry_year": 2026,
                "primary_routes": 200,
                "stable_share": None,
                "coefficient": 0.98,
                "standard_error": 0.01,
            },
            {
                "record_type": "entry_path_dependence_regression",
                "horizon_days": 30,
                "sample": "non_weth_endpoint",
                "outcome": "stable_share",
                "predictor": "entry_stable_share",
                "entry_year": None,
                "primary_routes": None,
                "stable_share": None,
                "coefficient": 0.80,
                "standard_error": 0.05,
                "coefficient_per_10pp_entry_share": 0.080,
                "standard_error_per_10pp_entry_share": 0.005,
                "p_value": 0.001,
                "observations": 1000,
            },
            {
                "record_type": "entry_path_dependence_regression",
                "horizon_days": 120,
                "sample": "non_weth_endpoint",
                "outcome": "stable_share",
                "predictor": "entry_stable_share",
                "entry_year": None,
                "primary_routes": None,
                "stable_share": None,
                "coefficient": 0.70,
                "standard_error": 0.08,
                "coefficient_per_10pp_entry_share": 0.070,
                "standard_error_per_10pp_entry_share": 0.008,
                "p_value": 0.001,
                "observations": 900,
            },
            {
                "record_type": "entry_path_dependence_regression",
                "horizon_days": 120,
                "sample": "non_weth_endpoint",
                "outcome": "stable_dominant_followup",
                "predictor": "entry_stable_dominant",
                "entry_year": None,
                "primary_routes": None,
                "stable_share": None,
                "coefficient": 0.60,
                "standard_error": 0.10,
                "p_value": 0.001,
                "observations": 900,
            },
            {
                "record_type": "entry_path_dependence_direct_route_support",
                "horizon_days": 120,
                "sample": "non_weth_endpoint",
                "direct_route_bucket": "no_direct_route",
                "observations": 512000,
                "entry_date_clusters": 243,
                "entry_primary_routes": 653000,
                "followup_primary_routes": 1950000,
            },
            {
                "record_type": "entry_path_dependence_direct_route_support",
                "horizon_days": 120,
                "sample": "non_weth_endpoint",
                "direct_route_bucket": "direct_route_present",
                "observations": 181,
                "entry_date_clusters": 80,
                "entry_primary_routes": 8000,
                "followup_primary_routes": 64000,
            },
            {
                "record_type": "entry_path_dependence_direct_route_regression",
                "horizon_days": 120,
                "sample": "non_weth_endpoint",
                "direct_route_bucket": "no_direct_route",
                "outcome": "stable_share",
                "predictor": "entry_stable_share",
                "coefficient_per_10pp_entry_share": 0.089,
                "standard_error_per_10pp_entry_share": 0.013,
                "p_value": 0.001,
                "observations": 512000,
            },
            {
                "record_type": "entry_value_path_dependence_regression",
                "horizon_days": 30,
                "sample": "non_weth_endpoint_value_supported",
                "outcome": "stable_value_share",
                "predictor": "entry_stable_value_share",
                "entry_year": None,
                "primary_routes": None,
                "stable_share": None,
                "coefficient": 0.90,
                "standard_error": 0.10,
                "coefficient_per_10pp_entry_value_share": 0.090,
                "standard_error_per_10pp_entry_value_share": 0.010,
                "p_value": 0.001,
                "observations": 510000,
            },
            {
                "record_type": "entry_value_path_dependence_regression",
                "horizon_days": 120,
                "sample": "non_weth_endpoint_value_supported",
                "outcome": "stable_value_share",
                "predictor": "entry_stable_value_share",
                "entry_year": None,
                "primary_routes": None,
                "stable_share": None,
                "coefficient": 0.78,
                "standard_error": 0.14,
                "coefficient_per_10pp_entry_value_share": 0.078,
                "standard_error_per_10pp_entry_value_share": 0.014,
                "p_value": 0.001,
                "observations": 428000,
            },
            {
                "record_type": "entry_regime_hysteresis",
                "horizon_days": 30,
                "entry_year": 2026,
                "entry_type": "stable_dominant_entry",
                "pairs": 20,
                "pairs_trading_again": 18,
                "primary_routes": 1,
                "stable_share": 0.0,
                "never_left_share_retrade": 0.92,
                "mean_stable_majority_day_share": 0.99,
            },
            {
                "record_type": "entry_regime_hysteresis",
                "horizon_days": 120,
                "entry_year": 2026,
                "entry_type": "stable_dominant_entry",
                "pairs": 20,
                "pairs_trading_again": 18,
                "primary_routes": 1,
                "stable_share": 0.0,
                "never_left_share_retrade": 0.95,
                "mean_stable_majority_day_share": 0.99,
            },
            {
                "record_type": "entry_endpoint_class",
                "entry_year": 2024,
                "endpoint_class": "non_weth_endpoint",
                "primary_routes": 90,
                "stable_share": 0.01,
                "route_mass_share": 0.90,
            },
            {
                "record_type": "entry_endpoint_class",
                "entry_year": 2026,
                "endpoint_class": "non_weth_endpoint",
                "primary_routes": 80,
                "stable_share": 0.08,
                "route_mass_share": 0.80,
            },
            {
                "record_type": "entry_endpoint_class",
                "entry_year": 2026,
                "endpoint_class": "weth_endpoint",
                "primary_routes": 20,
                "stable_share": 1.0,
                "route_mass_share": 0.20,
            },
            {
                "record_type": "entry_stable_candidate",
                "entry_year": 2026,
                "candidate_symbol": "USDC",
                "primary_routes": None,
                "stable_share": None,
                "stable_entry_route_share": 0.738,
            },
            {
                "record_type": "entry_stable_candidate",
                "entry_year": 2026,
                "candidate_symbol": "USDT",
                "primary_routes": None,
                "stable_share": None,
                "stable_entry_route_share": 0.258,
            },
            {
                "record_type": "entry_stable_candidate_persistence",
                "horizon_days": 30,
                "entry_year": 2026,
                "entry_candidate_symbol": "USDC",
                "primary_routes": None,
                "stable_share": None,
                "own_candidate_followup_share": 0.873,
            },
            {
                "record_type": "entry_stable_candidate_persistence",
                "horizon_days": 30,
                "entry_year": 2026,
                "entry_candidate_symbol": "USDT",
                "primary_routes": None,
                "stable_share": None,
                "own_candidate_followup_share": 0.946,
            },
            {
                "record_type": "entry_stable_candidate_persistence",
                "horizon_days": 120,
                "entry_year": 2026,
                "entry_candidate_symbol": "USDC",
                "primary_routes": None,
                "stable_share": None,
                "own_candidate_followup_share": 0.883,
            },
            {
                "record_type": "entry_stable_candidate_persistence",
                "horizon_days": 120,
                "entry_year": 2026,
                "entry_candidate_symbol": "USDT",
                "primary_routes": None,
                "stable_share": None,
                "own_candidate_followup_share": 0.877,
            },
            {
                "record_type": "entry_stable_candidate_identity_regression",
                "horizon_days": 30,
                "sample": "non_weth_stable_entry_candidate",
                "outcome": "own_candidate_followup_share",
                "predictor": "entry_candidate_share",
                "primary_routes": None,
                "stable_share": None,
                "coefficient_per_10pp_entry_candidate_share": 0.095,
                "standard_error_per_10pp_entry_candidate_share": 0.004,
                "p_value": 0.001,
                "observations": 12000,
            },
            {
                "record_type": "entry_stable_candidate_identity_regression",
                "horizon_days": 120,
                "sample": "non_weth_stable_entry_candidate",
                "outcome": "own_candidate_followup_share",
                "predictor": "entry_candidate_share",
                "primary_routes": None,
                "stable_share": None,
                "coefficient_per_10pp_entry_candidate_share": 0.092,
                "standard_error_per_10pp_entry_candidate_share": 0.007,
                "p_value": 0.001,
                "observations": 9000,
            },
            {
                "record_type": "entry_future_activity_regression",
                "horizon_days": 120,
                "sample": "non_weth_endpoint",
                "specification": "entry_stable_present",
                "outcome": "log_future_primary_routes",
                "predictor": "entry_stable_present",
                "primary_routes": None,
                "stable_share": None,
                "coefficient_pct": 9.2,
                "standard_error_pct": 1.7,
                "p_value": 0.001,
                "observations": 512201,
            },
            {
                "record_type": "entry_future_activity_regression",
                "horizon_days": 120,
                "sample": "non_weth_endpoint",
                "specification": "entry_stable_present",
                "outcome": "future_retrade",
                "predictor": "entry_stable_present",
                "primary_routes": None,
                "stable_share": None,
                "coefficient": 0.058,
                "standard_error": 0.007,
                "p_value": 0.001,
                "observations": 512201,
            },
            {
                "record_type": "entry_driver_regression",
                "endpoint_class": "non_weth_endpoint",
                "outcome": "stable_share",
                "predictor": "is_2026",
                "coefficient": 0.043,
                "standard_error": 0.004,
                "primary_routes": None,
                "stable_share": None,
            },
            {
                "record_type": "entry_driver_regression",
                "endpoint_class": "non_weth_endpoint",
                "outcome": "stable_share",
                "predictor": "is_2026_x_stable_endpoint",
                "coefficient": 0.057,
                "standard_error": 0.013,
                "primary_routes": None,
                "stable_share": None,
            },
            {
                "record_type": "entry_route_architecture_regression",
                "endpoint_class": "non_weth_endpoint",
                "outcome": "stable_share",
                "predictor": "is_2026_x_direct_share",
                "coefficient": 0.50,
                "standard_error": 0.14,
                "p_value": 0.001,
                "primary_routes": None,
                "stable_share": None,
            },
            {
                "record_type": "entry_route_architecture_regression",
                "endpoint_class": "non_weth_endpoint",
                "outcome": "stable_share",
                "predictor": "is_2026_x_complex_share",
                "coefficient": 0.36,
                "standard_error": 0.12,
                "p_value": 0.002,
                "primary_routes": None,
                "stable_share": None,
            },
            {
                "record_type": "entry_secure_volume_class",
                "entry_year": 2026,
                "secure_volume_class": "stable_endpoint",
                "primary_routes": 35,
                "stable_share": 0.18,
                "route_mass_share": 0.16,
            },
            {
                "record_type": "entry_secure_volume_class",
                "entry_year": 2026,
                "secure_volume_class": "other_non_weth_endpoint",
                "primary_routes": 142,
                "stable_share": 0.05,
                "route_mass_share": 0.84,
            },
            {
                "record_type": "entry_secure_volume_gap_change",
                "baseline_year": 2024,
                "comparison_year": 2026,
                "gap_change": 0.10,
            },
            {
                "record_type": "entry_secure_volume_regression",
                "endpoint_class": "non_weth_endpoint",
                "outcome": "stable_share",
                "predictor": "is_2026_x_stable_endpoint",
                "coefficient": 0.024,
                "standard_error": 0.010,
                "p_value": 0.02,
                "primary_routes": None,
                "stable_share": None,
            },
        ]
    )
    rendered = render_vehicle_formation_deck_values(estimates)
    assert "\\FormationEntryStableShareBase" in rendered
    assert "5.0\\%" in rendered
    assert "$+97.0$ pp" in rendered
    assert "$+98.0$ pp" in rendered
    assert "\\FormationPathEntryShareThirtyCoef" in rendered
    assert "\\FormationPathEntryShareOneTwentyCoef" in rendered
    assert "\\FormationPathDominantOneTwentyCoef" in rendered
    assert "\\FormationNoDirectPathEntryShareOneTwentyCoef" in rendered
    assert "\\FormationDirectPresentPathRowsOneTwenty" in rendered
    assert "\\FormationValuePathEntryShareThirtyCoef" in rendered
    assert "\\FormationValuePathEntryShareOneTwentyCoef" in rendered
    assert "$+9.0$ pp" in rendered
    assert "\\FormationNonWethEntryStableShareEnd" in rendered
    assert "\\FormationStableEntryTopTwoShareEnd" in rendered
    assert "99.6\\%" in rendered
    assert "\\FormationUSDCEntryOwnThirty" in rendered
    assert "\\FormationIdentityPathOneTwentyCoef" in rendered
    assert "\\FormationStablePresentFutureRoutesCoef" in rendered
    assert "$+9.2\\%$" in rendered
    assert "\\FormationStableHysteresisThirtyRetrade" in rendered
    assert "94.6\\%" in rendered
    assert "\\FormationNonWethYearDriver" in rendered
    assert "\\FormationRouteArchDirectShareDriver" in rendered
    assert "\\FormationRouteArchComplexShareDriver" in rendered
    assert "\\FormationSecureStableEndpointShareEnd" in rendered
    assert "$+10.0$ pp" in rendered
    assert "\\FormationSecureVolumeDriver" in rendered
