from __future__ import annotations

import pandas as pd

from scripts.tabulate.build_liquidity_provision_behavior_deck_values import (
    render_liquidity_provision_behavior_deck_values,
)


def test_liquidity_behavior_values_render_from_guarded_rows() -> None:
    rows = [
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "daily_leader_alignment",
            "days": 100,
            "weth_capital_leader_share": 1.0,
            "stable_excess_leader_share": 0.8,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "annual_stable_allocation",
            "year": 2024,
            "stable_capital_share": 0.2,
            "stable_intermediary_route_share": 0.3,
            "stable_route_to_capital_ratio": 1.5,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "annual_stable_allocation",
            "year": 2026,
            "stable_capital_share": 0.1,
            "stable_intermediary_route_share": 0.5,
            "stable_route_to_capital_ratio": 5.0,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "level_association",
            "outcome": "intermediary_episode_share",
            "predictor": "v2_log1p_deposited_capital_usd",
            "coefficient": 0.01,
            "standard_error": 0.002,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "level_association",
            "outcome": "vehicle_excess_use_count_ratio",
            "predictor": "v2_log1p_deposited_capital_usd",
            "coefficient": 0.5,
            "standard_error": 0.04,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "daily_route_capital_gap_change",
            "gap_name": "stable_route_capital_gap",
            "change": 0.33,
            "standard_error": 0.01,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "daily_route_capital_gap_change",
            "gap_name": "weth_route_capital_gap",
            "change": -0.36,
            "standard_error": 0.02,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "within_day_route_capital_gap_association",
            "outcome": "route_capital_gap_5",
            "predictor": "is_stable",
            "coefficient": 0.13,
            "standard_error": 0.01,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_closing",
            "horizon_days": 30,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "predictor": "route_capital_gap_5",
            "coefficient": 0.06,
            "standard_error": 0.01,
            "coefficient_per_10pp_gap": 0.006,
            "standard_error_per_10pp_gap": 0.001,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_closing",
            "horizon_days": 120,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "predictor": "route_capital_gap_5",
            "coefficient": 0.16,
            "standard_error": 0.01,
            "coefficient_per_10pp_gap": 0.016,
            "standard_error_per_10pp_gap": 0.001,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_closing_stable_interaction",
            "horizon_days": 30,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.10,
            "standard_error": 0.01,
            "coefficient_per_10pp_gap": 0.010,
            "standard_error_per_10pp_gap": 0.001,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_closing_stable_interaction",
            "horizon_days": 120,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.18,
            "standard_error": 0.01,
            "coefficient_per_10pp_gap": 0.018,
            "standard_error_per_10pp_gap": 0.001,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_asymmetry",
            "horizon_days": 30,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "predictor": "stable_total_negative_route_capital_gap_5",
            "coefficient": 0.40,
            "standard_error": 0.08,
            "coefficient_per_10pp_gap": 0.040,
            "standard_error_per_10pp_gap": 0.008,
            "effect_per_10pp_stable_overcapitalization": -0.040,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_asymmetry",
            "horizon_days": 120,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "predictor": "stable_total_negative_route_capital_gap_5",
            "coefficient": 0.70,
            "standard_error": 0.09,
            "coefficient_per_10pp_gap": 0.070,
            "standard_error_per_10pp_gap": 0.009,
            "effect_per_10pp_stable_overcapitalization": -0.070,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_extensive_margin",
            "horizon_days": 30,
            "outcome": "future_log_venue_count_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.05,
            "standard_error": 0.01,
            "coefficient_per_10pp_gap": 0.005,
            "standard_error_per_10pp_gap": 0.001,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_extensive_margin",
            "horizon_days": 120,
            "outcome": "future_log_venue_count_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.06,
            "standard_error": 0.02,
            "coefficient_per_10pp_gap": 0.006,
            "standard_error_per_10pp_gap": 0.002,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_extensive_margin",
            "horizon_days": 120,
            "outcome": "future_log_pool_count_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": -0.20,
            "standard_error": 0.05,
            "coefficient_per_10pp_gap": -0.020,
            "standard_error_per_10pp_gap": 0.005,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "capital_concentration_year",
            "year": 2024,
            "candidate_group": "stable_candidates",
            "capital_weighted_top_pool_share": 0.44,
            "capital_weighted_pool_hhi": 0.30,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "capital_concentration_year",
            "year": 2026,
            "candidate_group": "stable_candidates",
            "capital_weighted_top_pool_share": 0.52,
            "capital_weighted_pool_hhi": 0.40,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "capital_concentration_year",
            "year": 2026,
            "candidate_group": "nonstable_candidates",
            "capital_weighted_top_pool_share": 0.12,
            "capital_weighted_pool_hhi": 0.08,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_concentration_response",
            "horizon_days": 120,
            "outcome": "future_top_pool_share_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.24,
            "standard_error": 0.10,
            "coefficient_per_10pp_gap": 0.024,
            "standard_error_per_10pp_gap": 0.010,
            "p_value": 0.02,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_concentration_response",
            "horizon_days": 120,
            "outcome": "future_pool_hhi_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.27,
            "standard_error": 0.10,
            "coefficient_per_10pp_gap": 0.027,
            "standard_error_per_10pp_gap": 0.010,
            "p_value": 0.01,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_concentration_response",
            "horizon_days": 120,
            "outcome": "future_log_effective_pool_count_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": -0.80,
            "standard_error": 0.25,
            "coefficient_per_10pp_gap": -0.080,
            "standard_error_per_10pp_gap": 0.025,
            "p_value": 0.01,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_concentration_response",
            "horizon_days": 120,
            "outcome": "future_pool_count_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 34.0,
            "standard_error": 13.0,
            "coefficient_per_10pp_gap": 3.4,
            "standard_error_per_10pp_gap": 1.3,
            "p_value": 0.01,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_same_pool_reallocation",
            "horizon_days": 120,
            "outcome": "future_log_pool_candidate_capital_change",
            "predictor": "route_capital_gap_5",
            "coefficient": 0.20,
            "standard_error": 0.05,
            "coefficient_per_10pp_gap": 0.020,
            "standard_error_per_10pp_gap": 0.005,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_same_pool_reallocation",
            "horizon_days": 120,
            "outcome": "future_log_pool_candidate_capital_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.05,
            "standard_error": 0.08,
            "coefficient_per_10pp_gap": 0.005,
            "standard_error_per_10pp_gap": 0.008,
            "p_value": 0.50,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_v3_fee_incidence",
            "horizon_days": 120,
            "outcome": "future_log_fees_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.01,
            "standard_error": 0.08,
            "coefficient_per_10pp_gap": 0.001,
            "standard_error_per_10pp_gap": 0.008,
            "p_value": 0.90,
            "n_observations": 2000,
            "pool_count": 200,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_v3_fee_incidence",
            "horizon_days": 120,
            "outcome": "future_log_volume_change",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.15,
            "standard_error": 0.11,
            "coefficient_per_10pp_gap": 0.015,
            "standard_error_per_10pp_gap": 0.011,
            "p_value": 0.17,
            "n_observations": 2000,
            "pool_count": 200,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_v3_lp_action",
            "horizon_days": 30,
            "outcome": "future_log1p_v3_mint_events",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 6.0,
            "standard_error": 0.4,
            "coefficient_per_10pp_gap": 0.60,
            "standard_error_per_10pp_gap": 0.04,
            "p_value": 0.001,
            "n_observations": 2000,
            "date_clusters": 400,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_v3_lp_action",
            "horizon_days": 30,
            "outcome": "future_log1p_v3_total_lp_actions",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 5.8,
            "standard_error": 0.4,
            "coefficient_per_10pp_gap": 0.58,
            "standard_error_per_10pp_gap": 0.04,
            "p_value": 0.001,
            "n_observations": 2000,
            "date_clusters": 400,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_v3_lp_action",
            "horizon_days": 30,
            "outcome": "future_v3_net_mint_event_balance",
            "predictor": "stable_total_route_capital_gap_5",
            "coefficient": 0.18,
            "standard_error": 0.02,
            "coefficient_per_10pp_gap": 0.018,
            "standard_error_per_10pp_gap": 0.002,
            "p_value": 0.001,
            "n_observations": 2000,
            "date_clusters": 400,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_candidate_specific",
            "horizon_days": 120,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "candidate_symbol": "DAI",
            "coefficient": 0.30,
            "standard_error": 0.02,
            "coefficient_per_10pp_gap": 0.030,
            "standard_error_per_10pp_gap": 0.002,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_candidate_specific",
            "horizon_days": 120,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "candidate_symbol": "USDC",
            "coefficient": 0.08,
            "standard_error": 0.01,
            "coefficient_per_10pp_gap": 0.008,
            "standard_error_per_10pp_gap": 0.001,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_candidate_specific",
            "horizon_days": 120,
            "outcome": "future_v2_five_candidate_capital_share_change",
            "candidate_symbol": "USDT",
            "coefficient": 0.02,
            "standard_error": 0.01,
            "coefficient_per_10pp_gap": 0.002,
            "standard_error_per_10pp_gap": 0.001,
            "p_value": 0.20,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_candidate_specific",
            "horizon_days": 120,
            "outcome": "future_v2_log1p_deposited_capital_usd_change",
            "candidate_symbol": "USDC",
            "coefficient": 1.40,
            "standard_error": 0.20,
            "coefficient_per_10pp_gap": 0.140,
            "standard_error_per_10pp_gap": 0.020,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "route_capital_gap_candidate_specific",
            "horizon_days": 120,
            "outcome": "future_v2_log1p_deposited_capital_usd_change",
            "candidate_symbol": "USDT",
            "coefficient": 0.70,
            "standard_error": 0.20,
            "coefficient_per_10pp_gap": 0.070,
            "standard_error_per_10pp_gap": 0.020,
            "p_value": 0.02,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "stable_basket_gap_portfolio_rebalancing",
            "model_id": "activity_controls",
            "horizon_days": 30,
            "outcome": "future_stable_capital_share_change",
            "predictor": "stable_route_capital_gap",
            "coefficient": 0.08,
            "standard_error": 0.03,
            "coefficient_per_10pp_gap": 0.008,
            "standard_error_per_10pp_gap": 0.003,
            "p_value": 0.02,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "stable_basket_gap_portfolio_rebalancing",
            "model_id": "activity_controls",
            "horizon_days": 120,
            "outcome": "future_stable_capital_share_change",
            "predictor": "stable_route_capital_gap",
            "coefficient": 0.23,
            "standard_error": 0.05,
            "coefficient_per_10pp_gap": 0.023,
            "standard_error_per_10pp_gap": 0.005,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "stable_basket_gap_portfolio_rebalancing",
            "model_id": "activity_controls",
            "horizon_days": 120,
            "outcome": "future_weth_capital_share_change",
            "predictor": "stable_route_capital_gap",
            "coefficient": -0.20,
            "standard_error": 0.05,
            "coefficient_per_10pp_gap": -0.020,
            "standard_error_per_10pp_gap": 0.005,
            "p_value": 0.001,
        },
        {
            "analysis_status": "exploratory_descriptive",
            "record_type": "stable_basket_gap_portfolio_rebalancing",
            "model_id": "activity_controls",
            "horizon_days": 120,
            "outcome": "future_wbtc_capital_share_change",
            "predictor": "stable_route_capital_gap",
            "coefficient": -0.02,
            "standard_error": 0.02,
            "coefficient_per_10pp_gap": -0.002,
            "standard_error_per_10pp_gap": 0.002,
            "p_value": 0.40,
        },
    ]
    rendered = render_liquidity_provision_behavior_deck_values(pd.DataFrame(rows))
    assert "\\LiqBehWethCapitalLeaderDays" in rendered
    assert "\\LiqBehStableRouteCapitalRatioEnd" in rendered
    assert "\\LiqBehStableGapChange" in rendered
    assert "\\LiqBehStableControlledGapCoef" in rendered
    assert "\\LiqBehGapCloseMonthCoef" in rendered
    assert "\\LiqBehStableGapCloseMonthCoef" in rendered
    assert "\\LiqBehStableOverhangMonthCoef" in rendered
    assert "\\LiqBehStableVenueMonthCoef" in rendered
    assert "\\LiqBehStablePoolLongCoef" in rendered
    assert "\\LiqBehSamePoolLongCoef" in rendered
    assert "\\LiqBehStableSamePoolLongCoef" in rendered
    assert "\\LiqBehStableBasketGapLongCoef" in rendered
    assert "\\LiqBehWethBasketGapLongCoef" in rendered
    assert "\\LiqBehStableFeeLongCoef" in rendered
    assert "\\LiqBehStableVolumeLongCoef" in rendered
    assert "\\LiqBehStableVThreeMintMonthCoef" in rendered
    assert "\\LiqBehStableVThreeNetMintMonthCoef" in rendered
    assert "\\LiqBehUsdcGapCloseLongCoef" in rendered
    assert "\\LiqBehDaiGapCloseLongCoef" in rendered
    assert "\\LiqBehUsdtLogGapCloseLongCoef" in rendered
    assert "5.0\\times" in rendered
