"""Reusable LaTeX table helpers for DVC paper exhibits."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from ddvc.variable_registry import SUMMARY_SPECS, specs_by_group


@dataclass(frozen=True)
class SummaryRow:
    panel: str
    variable: str
    observations: int
    mean: float
    std_dev: float
    p25: float
    median: float
    p75: float


def latex_escape(value: object) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def latex_texttt_breakable(value: str) -> str:
    parts = [latex_escape(part) for part in value.split("_")]
    return r"\texttt{" + r"\_\allowbreak{}".join(parts) + "}"


def format_count(value: int) -> str:
    return f"{int(value):,}"


def format_number(value: float) -> str:
    abs_value = abs(value)
    if abs_value >= 1_000:
        return f"{value:,.0f}"
    if abs_value >= 100:
        return f"{value:,.1f}"
    return f"{value:,.2f}"


def render_variable_notation_latex() -> str:
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\caption{Variable notation and construction}",
        r"\label{tab:variable-notation}",
        r"\scriptsize",
        r"\begin{tabular}{@{}p{0.17\linewidth}p{0.18\linewidth}p{0.18\linewidth}p{0.39\linewidth}@{}}",
        r"\toprule",
        r"Notation & Observation-table column & Unit & Construction \\",
        r"\midrule",
    ]
    first_group = True
    for group, specs in specs_by_group().items():
        if not first_group:
            lines.append(r"\addlinespace")
        first_group = False
        lines.append(rf"\multicolumn{{4}}{{l}}{{\textit{{{latex_escape(group)}}}}} \\")
        for spec in specs:
            lines.append(
                " & ".join(
                    [
                        spec.notation,
                        latex_texttt_breakable(spec.column),
                        latex_escape(spec.unit),
                        latex_escape(spec.construction),
                    ]
                )
                + r" \\"
            )
    note = (
        "Notes: This table defines the notation and implemented columns used to construct the "
        "canonical observations table. The observations table is generated by "
        "\\texttt{scripts/process/build\\_observations\\_table.py} and is the input to "
        "summary statistics, regressions, and exploratory figures."
    )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\vspace{0.35em}",
            r"\begin{minipage}{0.98\linewidth}",
            rf"\footnotesize {note}",
            r"\end{minipage}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def _summary(panel: str, variable: str, values: pd.Series) -> SummaryRow:
    clean = pd.to_numeric(values, errors="coerce").dropna()
    if clean.empty:
        raise ValueError(f"No non-missing observations for {panel}: {variable}")
    return SummaryRow(
        panel=panel,
        variable=variable,
        observations=int(clean.shape[0]),
        mean=float(clean.mean()),
        std_dev=float(clean.std()),
        p25=float(clean.quantile(0.25)),
        median=float(clean.median()),
        p75=float(clean.quantile(0.75)),
    )


def build_summary_rows(observations_table: Path) -> list[SummaryRow]:
    if not observations_table.exists():
        raise FileNotFoundError(
            f"Required input is missing: {observations_table}. "
            "Run .venv/bin/python scripts/process/build_observations_table.py first."
        )

    panel = pd.read_parquet(observations_table)
    panel["date"] = pd.to_datetime(panel["date"]).dt.normalize()
    day_panel = panel.drop_duplicates("date").sort_values("date")

    panel_order = {
        "Panel A. Daily route activity": 0,
        "Panel B. Vehicle-use measures, token-day": 1,
        "Panel C. Liquidity and route-cost opportunity": 2,
        "Panel D. Settlement-transfer sample": 3,
    }
    specs = sorted(
        SUMMARY_SPECS,
        key=lambda spec: (
            panel_order.get(spec.summary_panel or spec.group, 99),
            SUMMARY_SPECS.index(spec),
        ),
    )

    rows: list[SummaryRow] = []
    for spec in specs:
        if spec.column not in panel.columns:
            raise KeyError(f"Registered summary column missing from observations table: {spec.column}")
        source = day_panel if spec.summary_level == "day" else panel
        label = spec.summary_label or spec.name
        values = source[spec.column] * spec.summary_scale
        rows.append(_summary(spec.summary_panel or spec.group, label, values))
    return rows


def render_summary_statistics_latex(rows: list[SummaryRow]) -> str:
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\caption{Summary statistics}",
        r"\label{tab:summary-statistics}",
        r"\small",
        r"\begin{tabular}{@{}lrrrrrr@{}}",
        r"\toprule",
        r"Variable & Obs. & Mean & Std. dev. & p25 & Median & p75 \\",
        r"\midrule",
    ]

    current_panel: str | None = None
    for row in rows:
        if row.panel != current_panel:
            if current_panel is not None:
                lines.append(r"\addlinespace")
            lines.append(rf"\multicolumn{{7}}{{l}}{{\textit{{{latex_escape(row.panel)}}}}} \\")
            current_panel = row.panel
        cells = [
            latex_escape(row.variable),
            format_count(row.observations),
            format_number(row.mean),
            format_number(row.std_dev),
            format_number(row.p25),
            format_number(row.median),
            format_number(row.p75),
        ]
        lines.append(" & ".join(cells) + r" \\")

    note = (
        "Notes: The table reports summary statistics from the canonical observations table "
        "generated by scripts/process/build_observations_table.py. Day-level variables are "
        "summarized after deduplicating dates; token-day and settlement variables use their "
        "available observations in the same table. BridgeShare uses indirect route volume as "
        "the denominator; all-route bridge share uses total route volume."
    )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\vspace{0.35em}",
            r"\begin{minipage}{0.98\linewidth}",
            rf"\footnotesize {latex_escape(note)}",
            r"\end{minipage}",
            r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"
