#!/usr/bin/env python3
"""Build display macros for the fixed-cohort conditioning of the vehicle rotation.

The rotation is measured on a population whose membership changes: corridors open
and close, and the candidates that intermediate a corridor come and go. These
macros carry the same share change re-estimated on cohorts that were active in
both endpoint years, together with the two facts a reader needs before spending
them. The first is the retained denominator mass, because a conditional estimate
on a cohort holding most of the economy means something different from one on a
cohort holding a tenth of it. The second is the universe gap between the pooled
change measured on the endpoint-candidate choice panel and the same change on the
type-level daily panel, which is what licenses reading these terms beside the
headline.

The pair-venue cohort's macros are emitted with their interval, not only their
standard error, because that cohort is the one whose count estimate lands near
zero and a near-zero estimate is only ever reportable as a bound.

Reads   output/exhibits/e0_vehicle_transition_fixed_opportunity_estimates.jsonl
        output/exhibits/e0_vehicle_transition_fixed_opportunity_support.jsonl
Writes  output/exhibits/vehicle_transition_fixed_opportunity_deck_values.tex
"""

from __future__ import annotations

import math

import pandas as pd

from ddvc.paths import OUTPUT_DIR
from ddvc.presentation import require_certified_presentation_source
from ddvc.provenance import stamp
from ddvc.runtime import atomic_output

ESTIMATES = (
    OUTPUT_DIR / "exhibits" / "e0_vehicle_transition_fixed_opportunity_estimates.jsonl"
)
SUPPORT = OUTPUT_DIR / "exhibits" / "e0_vehicle_transition_fixed_opportunity_support.jsonl"
DECK_VALUES = (
    OUTPUT_DIR / "exhibits" / "vehicle_transition_fixed_opportunity_deck_values.tex"
)
CODE_SOURCES = ["scripts/build_fixed_opportunity_deck_values.py"]

# The headline stratum is the exact two-leg route sample, read at share level so a
# conditional change and the pooled change it is compared against are in the same
# units. Log odds is published in the exhibit and deliberately not carried into
# prose macros.
SCOPE = "two_leg"
TRANSFORMATION = "share_level"
WEIGHTINGS = (("Count", "episode", "all_routes"), ("Value", "value", "within_20pct"))
COHORTS = (
    ("Pooled", "all_routes", "aggregate"),
    ("Pair", "persistent_pair", "conditional"),
    ("Candidate", "persistent_pair_candidate", "conditional"),
    ("Venue", "persistent_pair_venue_sequence", "conditional"),
)


def _row(frame: pd.DataFrame, **identity: object) -> pd.Series:
    selected = frame
    for key, value in identity.items():
        selected = selected[selected[key] == value]
    if len(selected) != 1:
        terms = ", ".join(f"{key}={value!r}" for key, value in identity.items())
        raise ValueError(
            f"fixed-opportunity exhibit requires one {terms} row; found {len(selected)}"
        )
    return selected.iloc[0]


def _pp(value: float, decimals: int = 2) -> str:
    return f"${100 * value:+.{decimals}f}$ pp"


def _se(value: float, decimals: int = 2) -> str:
    return f"{100 * value:.{decimals}f} pp"


def _share(value: float, decimals: int = 1) -> str:
    return f"{100 * value:.{decimals}f}\\%"


def render(estimates: pd.DataFrame, support: pd.DataFrame) -> str:
    lines = [
        "% Generated by scripts/build_fixed_opportunity_deck_values.py.",
        "% Fixed-cohort conditioning of the vehicle rotation, on the exact two-leg",
        "% sample and the native-plus-stable denominator. Provisional/E0 scope: the",
        "% estimates run on the released endpoint-candidate choice panel and are not",
        "% submission-authoritative until the findings freeze admits them.",
        "% Cohort membership is decided using both endpoint years, so a conditional",
        "% row is the change among continuously active cells, not the full-universe",
        "% change; always spend it beside its retained-mass macro.",
        "% Refresh by rerunning scripts/run_vehicle_transition_e0.py then this builder.",
    ]
    fitted = estimates[
        estimates["routing_scope"].eq(SCOPE) & estimates["transformation"].eq(TRANSFORMATION)
    ]
    mass = support[
        support["record_type"].eq("cohort_mass_ledger") & support["routing_scope"].eq(SCOPE)
    ]
    cells = support[
        support["record_type"].eq("cohort_cell_ledger") & support["routing_scope"].eq(SCOPE)
    ]
    for stem, weighting, value_support in WEIGHTINGS:
        for cohort_stem, cohort, role in COHORTS:
            row = _row(
                fitted,
                weighting=weighting,
                value_support=value_support,
                cohort=cohort,
                stratum_role=role,
            )
            for column in (
                "change",
                "hac_standard_error",
                "confidence_interval_lower",
                "confidence_interval_upper",
            ):
                if not math.isfinite(float(row[column])):
                    raise ValueError(f"{cohort_stem}{stem} has a non-finite {column}")
            lines += [
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}Change}}"
                f"{{{_pp(float(row['change']))}}}",
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}SE}}"
                f"{{{_se(float(row['hac_standard_error']))}}}",
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}CILower}}"
                f"{{{_pp(float(row['confidence_interval_lower']))}}}",
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}CIUpper}}"
                f"{{{_pp(float(row['confidence_interval_upper']))}}}",
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}Base}}"
                f"{{{_share(float(row['baseline_daily_mean']), 2)}}}",
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}End}}"
                f"{{{_share(float(row['comparison_daily_mean']), 2)}}}",
            ]
            if cohort_stem == "Pooled":
                continue
            weight = _row(
                mass, weighting=weighting, value_support=value_support, cohort=cohort
            )
            lines += [
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}MassBase}}"
                f"{{{_share(float(weight['baseline_denominator_share']))}}}",
                f"\\newcommand{{\\Fixed{cohort_stem}{stem}MassEnd}}"
                f"{{{_share(float(weight['comparison_denominator_share']))}}}",
            ]
        reconciliation = _row(
            support[support["record_type"].eq("universe_reconciliation")],
            routing_scope=SCOPE,
            transformation=TRANSFORMATION,
            weighting=weighting,
            value_support=value_support,
        )
        # Three decimals: the two universes agree far inside the second decimal, and
        # rounding that agreement to `0.00 pp` would read as a rounded number rather
        # than as the measured gap it is.
        lines.append(
            f"\\newcommand{{\\Fixed{stem}UniverseGap}}"
            f"{{{_se(float(reconciliation['absolute_difference']), 3)}}}"
        )
    for cohort_stem, cohort, _role in COHORTS:
        if cohort_stem == "Pooled":
            continue
        cell = _row(cells, cohort=cohort)
        lines += [
            f"\\newcommand{{\\Fixed{cohort_stem}Cells}}"
            f"{{{int(cell['persistent_cells']):,}}}",
            f"\\newcommand{{\\Fixed{cohort_stem}UniverseCells}}"
            f"{{{int(cell['endpoint_universe_cells']):,}}}",
        ]
    unsupported = support[support["record_type"].eq("unsupported_dimension")]
    if unsupported["fitted"].astype(bool).any():
        raise ValueError("an unsupported attack dimension is marked fitted")
    lines.append(
        f"\\newcommand{{\\FixedUnsupportedDimensions}}{{{len(unsupported):,}}}"
    )
    lines.append(f"\\newcommand{{\\FixedCohortDays}}{{{int(_pooled_days(fitted)):,}}}")
    return "\n".join(lines) + "\n"


def _pooled_days(fitted: pd.DataFrame) -> int:
    """Return the day count every headline row shares, refusing a ragged sample."""

    headline = fitted[fitted["stratum_role"].isin(("aggregate", "conditional"))]
    days = sorted(set(headline["days"].astype(int)))
    if len(days) != 1:
        raise ValueError(f"fixed-opportunity headline rows span uneven day counts: {days}")
    return days[0]


def main() -> None:
    provenance_inputs = []
    for path in (ESTIMATES, SUPPORT):
        provenance_inputs.extend((path, require_certified_presentation_source(path)))
    estimates = pd.read_json(ESTIMATES, lines=True)
    support = pd.read_json(SUPPORT, lines=True)
    rendered = render(estimates, support)
    with atomic_output(DECK_VALUES) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    stamp(
        DECK_VALUES,
        code_sources=CODE_SOURCES,
        inputs=provenance_inputs,
        rows=len(estimates) + len(support),
        notes=(
            "Display macros for the fixed-cohort conditioning of the vehicle-currency "
            "rotation, the denominator mass each cohort retains, the cells it keeps, "
            "the attack dimensions the released panel cannot fit, and the "
            "choice-universe versus type-panel gap."
        ),
    )
    print(f"wrote {DECK_VALUES.relative_to(OUTPUT_DIR.parent)}")


if __name__ == "__main__":
    main()
