#!/usr/bin/env python3
"""Build presentation macros from the current vehicle-pair decomposition."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import pandas as pd

from ddvc.paths import OUTPUT_DIR, REPO_ROOT
from ddvc.provenance import (
    code_fingerprint,
    describe_artifact_payload,
    sidecar_path,
    stamp,
)
from ddvc.runtime import atomic_output


DECOMPOSITION = OUTPUT_DIR / "exhibits" / "vehicle_transition_pair_decomposition.jsonl"
DECK_VALUES = OUTPUT_DIR / "exhibits" / "vehicle_transition_pair_decomposition_deck_values.tex"
CODE_SOURCES = ["scripts/build_vehicle_transition_pair_deck_values.py"]
SCOPES = ("pooled", "single_venue", "cross_venue")
TERMS = (
    "within_common",
    "common_pair_reweighting",
    "common_support_mass",
    "exclusive_pair_contribution",
)


def _signed_pp(value: float) -> str:
    points = 100 * value
    if abs(points) < 0.05:
        return "0.0\\,pp"
    return f"{points:+.1f}\\,pp"


def _share(value: float) -> str:
    return f"{100 * value:.1f}\\%"


def _raw_pp(value: float) -> str:
    return f"{100 * value:.9f}"


def _raw_pct(value: float) -> str:
    return f"{100 * value:.9f}"


def _scope_rows(decomposition: pd.DataFrame, metric: str) -> dict[str, pd.Series]:
    required = {
        "metric",
        "reporting_scope",
        "baseline_year",
        "comparison_year",
        "common_calendar_end",
        "common_month_days",
        "formula_id",
        "mechanism_status",
        "baseline_stable_share",
        "comparison_stable_share",
        "total_change",
        "support_and_exclusive_joint",
        "identity_error",
        *TERMS,
    }
    missing = sorted(required - set(decomposition.columns))
    if missing:
        raise ValueError(f"pair decomposition missing columns: {', '.join(missing)}")
    rows: dict[str, pd.Series] = {}
    for scope in SCOPES:
        selected = decomposition[
            decomposition["metric"].eq(metric)
            & decomposition["reporting_scope"].eq(scope)
        ]
        if len(selected) != 1:
            raise ValueError(
                f"pair decomposition requires exactly one {metric}/{scope} row; "
                f"found {len(selected)}"
            )
        row = selected.iloc[0]
        if int(row["baseline_year"]) != 2024 or int(row["comparison_year"]) != 2026:
            raise ValueError("pair decomposition must compare 2024 with 2026")
        if row["common_calendar_end"] != "06-30" or int(row["common_month_days"]) != 181:
            raise ValueError("pair decomposition does not use the locked common calendar")
        if row["formula_id"] != "midpoint_common_exclusive_support_v1":
            raise ValueError("pair decomposition formula differs from the locked identity")
        if row["mechanism_status"] != "descriptive_realised_composition_noncausal":
            raise ValueError("pair decomposition is not labelled as descriptive composition")
        numeric = [
            "baseline_stable_share",
            "comparison_stable_share",
            "total_change",
            "support_and_exclusive_joint",
            "identity_error",
            *TERMS,
        ]
        if not all(math.isfinite(float(row[column])) for column in numeric):
            raise ValueError("pair decomposition contains a non-finite accounting cell")
        if abs(float(row["identity_error"])) > 1e-12:
            raise ValueError("pair decomposition identity error exceeds tolerance")
        joint = float(row["common_support_mass"]) + float(
            row["exclusive_pair_contribution"]
        )
        if not math.isclose(
            float(row["support_and_exclusive_joint"]), joint, abs_tol=1e-12
        ):
            raise ValueError("pair decomposition joint support term does not reconcile")
        total = sum(float(row[column]) for column in TERMS)
        if not math.isclose(float(row["total_change"]), total, abs_tol=1e-12):
            raise ValueError("pair decomposition terms do not sum to the total change")
        if not math.isclose(
            float(row["baseline_stable_share"]) + total,
            float(row["comparison_stable_share"]),
            abs_tol=1e-12,
        ):
            raise ValueError("pair decomposition endpoints do not reconcile")
        rows[scope] = row
    return rows


def render_pair_decomposition_deck_values(decomposition: pd.DataFrame) -> str:
    """Render empirical cells while keeping evidence identity out of the PDF."""
    count = _scope_rows(decomposition, "count_share")
    value = _scope_rows(decomposition, "strict_intermediation_value_share")
    pooled = count["pooled"]
    lines = [
        "% Generated by scripts/build_vehicle_transition_pair_deck_values.py; do not edit.",
        f"\\newcommand{{\\PairPooledBase}}{{{_share(float(pooled['baseline_stable_share']))}}}",
        f"\\newcommand{{\\PairPooledEnd}}{{{_share(float(pooled['comparison_stable_share']))}}}",
        f"\\newcommand{{\\PairPooledTotal}}{{{_signed_pp(float(pooled['total_change']))}}}",
        f"\\newcommand{{\\PairPooledReweight}}{{{_signed_pp(float(pooled['common_pair_reweighting']))}}}",
        f"\\newcommand{{\\PairPooledSupportMass}}{{{_signed_pp(float(pooled['common_support_mass']))}}}",
        f"\\newcommand{{\\PairPooledExclusive}}{{{_signed_pp(float(pooled['exclusive_pair_contribution']))}}}",
        f"\\newcommand{{\\PairPooledWithin}}{{{_signed_pp(float(pooled['within_common']))}}}",
        f"\\newcommand{{\\PairPooledBaseRawPct}}{{{_raw_pct(float(pooled['baseline_stable_share']))}}}",
        f"\\newcommand{{\\PairPooledEndRawPct}}{{{_raw_pct(float(pooled['comparison_stable_share']))}}}",
        f"\\newcommand{{\\PairPooledReweightRawPP}}{{{_raw_pp(float(pooled['common_pair_reweighting']))}}}",
        f"\\newcommand{{\\PairPooledSupportMassRawPP}}{{{_raw_pp(float(pooled['common_support_mass']))}}}",
        f"\\newcommand{{\\PairPooledExclusiveRawPP}}{{{_raw_pp(float(pooled['exclusive_pair_contribution']))}}}",
        f"\\newcommand{{\\PairPooledWithinRawPP}}{{{_raw_pp(float(pooled['within_common']))}}}",
    ]
    for scope, suffix in (("single_venue", "Single"), ("cross_venue", "Cross")):
        row = count[scope]
        lines.extend(
            [
                f"\\newcommand{{\\Pair{suffix}Total}}{{{_signed_pp(float(row['total_change']))}}}",
                f"\\newcommand{{\\Pair{suffix}Within}}{{{_signed_pp(float(row['within_common']))}}}",
            ]
        )
    value_pooled = value["pooled"]
    lines.extend(
        [
            f"\\newcommand{{\\PairValueTotal}}{{{_signed_pp(float(value_pooled['total_change']))}}}",
            f"\\newcommand{{\\PairValueWithin}}{{{_signed_pp(float(value_pooled['within_common']))}}}",
            f"\\newcommand{{\\PairValueReweight}}{{{_signed_pp(float(value_pooled['common_pair_reweighting']))}}}",
            f"\\newcommand{{\\PairValueSupportMass}}{{{_signed_pp(float(value_pooled['common_support_mass']))}}}",
            f"\\newcommand{{\\PairValueExclusive}}{{{_signed_pp(float(value_pooled['exclusive_pair_contribution']))}}}",
        ]
    )
    return "\n".join(lines) + "\n"


def _require_certified_presentation_source(path: Path) -> Path:
    """Verify the committed exhibit boundary without reopening Studio's inputs.

    The data-owning checkout certifies the full upstream perimeter before it
    commits the exhibit and sidecar.  A presentation checkout verifies that
    committed payload/sidecar pair and the producer code, rather than trying to
    rehash the data host's 39 GB lineage.
    """
    provenance_path = sidecar_path(path)
    if not path.is_file() or not provenance_path.is_file():
        raise FileNotFoundError("pair decomposition payload or provenance is missing")
    record = json.loads(provenance_path.read_text(encoding="utf-8"))
    relative = path.resolve().relative_to(REPO_ROOT.resolve()).as_posix()
    if record.get("artefact") != relative:
        raise ValueError("pair decomposition provenance names a different artifact")
    observed_identity = describe_artifact_payload(path, artefact=path)
    if record.get("payload_identity") != observed_identity:
        raise ValueError("pair decomposition payload differs from its certified identity")
    sources = record.get("code_sources")
    if not isinstance(sources, list) or code_fingerprint(sources) != record.get(
        "code_fingerprint"
    ):
        raise ValueError("pair decomposition producer code differs from its certificate")
    if record.get("rows") != observed_identity.get("rows"):
        raise ValueError("pair decomposition row count differs from its certificate")
    return provenance_path


def run(*, decomposition_path: Path = DECOMPOSITION, output_path: Path = DECK_VALUES) -> int:
    provenance_path = _require_certified_presentation_source(decomposition_path)
    decomposition = pd.read_json(decomposition_path, lines=True)
    rendered = render_pair_decomposition_deck_values(decomposition)
    with atomic_output(output_path) as temporary:
        temporary.write_text(rendered, encoding="utf-8")
    stamp(
        output_path,
        code_sources=CODE_SOURCES,
        inputs=[decomposition_path, provenance_path],
        rows=len(decomposition),
        notes=(
            "Presentation macros for the exact descriptive pair-composition "
            "accounting; evidence status and identities remain source-only."
        ),
    )
    print(f"wrote {output_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--decomposition", type=Path, default=DECOMPOSITION)
    parser.add_argument("--output", type=Path, default=DECK_VALUES)
    args = parser.parse_args()
    return run(decomposition_path=args.decomposition, output_path=args.output)


if __name__ == "__main__":
    raise SystemExit(main())
